// Code generated by ogen, DO NOT EDIT.

package apispec

// setDefaults set default value of fields.
func (s *CreateSandboxVolumeRequest) setDefaults() {
	{
		val := int64(0)
		s.DefaultPosixUID.SetTo(val)
	}
	{
		val := int64(0)
		s.DefaultPosixGid.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FunctionDeployRequest) setDefaults() {
	{
		val := bool(true)
		s.Activate.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FunctionRevisionMount) setDefaults() {
	{
		val := bool(true)
		s.ReadOnly.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FunctionScalePolicy) setDefaults() {
	{
		val := int32(1)
		s.MaxInstances.SetTo(val)
	}
	{
		val := int32(1)
		s.TargetConcurrency.SetTo(val)
	}
	{
		val := int32(300)
		s.IdleTimeoutSeconds.SetTo(val)
	}
	{
		val := int32(90)
		s.StartupTimeoutSeconds.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SandboxAppServiceRouteAuth) setDefaults() {
	{
		val := SandboxAppServiceRouteAuthMode("none")
		s.Mode = val
	}
}

// setDefaults set default value of fields.
func (s *SandboxConfig) setDefaults() {
	{
		val := bool(true)
		s.AutoResume.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SandboxUpdateConfig) setDefaults() {
	{
		val := bool(true)
		s.AutoResume.SetTo(val)
	}
}
