// Code generated by ogen, DO NOT EDIT.

package apispec

// APIKeysIDDeactivatePostParams is parameters of POST /api-keys/{id}/deactivate operation.
type APIKeysIDDeactivatePostParams struct {
	ID string
}

// APIKeysIDDeleteParams is parameters of DELETE /api-keys/{id} operation.
type APIKeysIDDeleteParams struct {
	ID string
}

// APIV1SandboxesGetParams is parameters of GET /api/v1/sandboxes operation.
type APIV1SandboxesGetParams struct {
	// Filter by sandbox status.
	Status OptAPIV1SandboxesGetStatus `json:",omitempty,omitzero"`
	// Filter by template ID.
	TemplateID OptString `json:",omitempty,omitzero"`
	// Filter by paused state.
	Paused OptBool `json:",omitempty,omitzero"`
	// Maximum number of results per page.
	Limit OptInt `json:",omitempty,omitzero"`
	// Pagination offset.
	Offset OptInt `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDContextsCtxIDDeleteParams is parameters of DELETE /api/v1/sandboxes/{id}/contexts/{ctx_id} operation.
type APIV1SandboxesIDContextsCtxIDDeleteParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDExecPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/exec operation.
type APIV1SandboxesIDContextsCtxIDExecPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDGetParams is parameters of GET /api/v1/sandboxes/{id}/contexts/{ctx_id} operation.
type APIV1SandboxesIDContextsCtxIDGetParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDInputPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/input operation.
type APIV1SandboxesIDContextsCtxIDInputPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDResizePostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/resize operation.
type APIV1SandboxesIDContextsCtxIDResizePostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDRestartPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/restart operation.
type APIV1SandboxesIDContextsCtxIDRestartPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDSignalPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/signal operation.
type APIV1SandboxesIDContextsCtxIDSignalPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDStatsGetParams is parameters of GET /api/v1/sandboxes/{id}/contexts/{ctx_id}/stats operation.
type APIV1SandboxesIDContextsCtxIDStatsGetParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDWsGetParams is parameters of GET /api/v1/sandboxes/{id}/contexts/{ctx_id}/ws operation.
type APIV1SandboxesIDContextsCtxIDWsGetParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsGetParams is parameters of GET /api/v1/sandboxes/{id}/contexts operation.
type APIV1SandboxesIDContextsGetParams struct {
	ID string
}

// APIV1SandboxesIDContextsPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts operation.
type APIV1SandboxesIDContextsPostParams struct {
	ID string
}

// APIV1SandboxesIDDeleteParams is parameters of DELETE /api/v1/sandboxes/{id} operation.
type APIV1SandboxesIDDeleteParams struct {
	ID string
}

// APIV1SandboxesIDExposedPortsDeleteParams is parameters of DELETE /api/v1/sandboxes/{id}/exposed-ports operation.
type APIV1SandboxesIDExposedPortsDeleteParams struct {
	ID string
}

// APIV1SandboxesIDExposedPortsGetParams is parameters of GET /api/v1/sandboxes/{id}/exposed-ports operation.
type APIV1SandboxesIDExposedPortsGetParams struct {
	ID string
}

// APIV1SandboxesIDExposedPortsPortDeleteParams is parameters of DELETE /api/v1/sandboxes/{id}/exposed-ports/{port} operation.
type APIV1SandboxesIDExposedPortsPortDeleteParams struct {
	ID   string
	Port int32
}

// APIV1SandboxesIDExposedPortsPutParams is parameters of PUT /api/v1/sandboxes/{id}/exposed-ports operation.
type APIV1SandboxesIDExposedPortsPutParams struct {
	ID string
}

// APIV1SandboxesIDFilesDeleteParams is parameters of DELETE /api/v1/sandboxes/{id}/files operation.
type APIV1SandboxesIDFilesDeleteParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesGetParams is parameters of GET /api/v1/sandboxes/{id}/files operation.
type APIV1SandboxesIDFilesGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesListGetParams is parameters of GET /api/v1/sandboxes/{id}/files/list operation.
type APIV1SandboxesIDFilesListGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesMovePostParams is parameters of POST /api/v1/sandboxes/{id}/files/move operation.
type APIV1SandboxesIDFilesMovePostParams struct {
	ID string
}

// APIV1SandboxesIDFilesPostParams is parameters of POST /api/v1/sandboxes/{id}/files operation.
type APIV1SandboxesIDFilesPostParams struct {
	ID        string
	Path      string
	Mkdir     OptBool `json:",omitempty,omitzero"`
	Recursive OptBool `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDFilesStatGetParams is parameters of GET /api/v1/sandboxes/{id}/files/stat operation.
type APIV1SandboxesIDFilesStatGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesWatchGetParams is parameters of GET /api/v1/sandboxes/{id}/files/watch operation.
type APIV1SandboxesIDFilesWatchGetParams struct {
	ID string
}

// APIV1SandboxesIDGetParams is parameters of GET /api/v1/sandboxes/{id} operation.
type APIV1SandboxesIDGetParams struct {
	ID string
}

// APIV1SandboxesIDNetworkGetParams is parameters of GET /api/v1/sandboxes/{id}/network operation.
type APIV1SandboxesIDNetworkGetParams struct {
	ID string
}

// APIV1SandboxesIDNetworkPutParams is parameters of PUT /api/v1/sandboxes/{id}/network operation.
type APIV1SandboxesIDNetworkPutParams struct {
	ID string
}

// APIV1SandboxesIDPausePostParams is parameters of POST /api/v1/sandboxes/{id}/pause operation.
type APIV1SandboxesIDPausePostParams struct {
	ID string
}

// APIV1SandboxesIDPutParams is parameters of PUT /api/v1/sandboxes/{id} operation.
type APIV1SandboxesIDPutParams struct {
	ID string
}

// APIV1SandboxesIDRefreshPostParams is parameters of POST /api/v1/sandboxes/{id}/refresh operation.
type APIV1SandboxesIDRefreshPostParams struct {
	ID string
}

// APIV1SandboxesIDResumePostParams is parameters of POST /api/v1/sandboxes/{id}/resume operation.
type APIV1SandboxesIDResumePostParams struct {
	ID string
}

// APIV1SandboxesIDSandboxvolumesMountPostParams is parameters of POST /api/v1/sandboxes/{id}/sandboxvolumes/mount operation.
type APIV1SandboxesIDSandboxvolumesMountPostParams struct {
	ID string
}

// APIV1SandboxesIDSandboxvolumesStatusGetParams is parameters of GET /api/v1/sandboxes/{id}/sandboxvolumes/status operation.
type APIV1SandboxesIDSandboxvolumesStatusGetParams struct {
	ID string
}

// APIV1SandboxesIDSandboxvolumesUnmountPostParams is parameters of POST /api/v1/sandboxes/{id}/sandboxvolumes/unmount operation.
type APIV1SandboxesIDSandboxvolumesUnmountPostParams struct {
	ID string
}

// APIV1SandboxesIDStatusGetParams is parameters of GET /api/v1/sandboxes/{id}/status operation.
type APIV1SandboxesIDStatusGetParams struct {
	ID string
}

// APIV1SandboxvolumesIDDeleteParams is parameters of DELETE /api/v1/sandboxvolumes/{id} operation.
type APIV1SandboxvolumesIDDeleteParams struct {
	ID string
}

// APIV1SandboxvolumesIDGetParams is parameters of GET /api/v1/sandboxvolumes/{id} operation.
type APIV1SandboxvolumesIDGetParams struct {
	ID string
}

// APIV1SandboxvolumesIDSnapshotsGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/snapshots operation.
type APIV1SandboxvolumesIDSnapshotsGetParams struct {
	ID string
}

// APIV1SandboxvolumesIDSnapshotsPostParams is parameters of POST /api/v1/sandboxvolumes/{id}/snapshots operation.
type APIV1SandboxvolumesIDSnapshotsPostParams struct {
	ID string
}

// APIV1SandboxvolumesIDSnapshotsSnapshotIDDeleteParams is parameters of DELETE /api/v1/sandboxvolumes/{id}/snapshots/{snapshot_id} operation.
type APIV1SandboxvolumesIDSnapshotsSnapshotIDDeleteParams struct {
	ID         string
	SnapshotID string
}

// APIV1SandboxvolumesIDSnapshotsSnapshotIDGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/snapshots/{snapshot_id} operation.
type APIV1SandboxvolumesIDSnapshotsSnapshotIDGetParams struct {
	ID         string
	SnapshotID string
}

// APIV1SandboxvolumesIDSnapshotsSnapshotIDRestorePostParams is parameters of POST /api/v1/sandboxvolumes/{id}/snapshots/{snapshot_id}/restore operation.
type APIV1SandboxvolumesIDSnapshotsSnapshotIDRestorePostParams struct {
	ID         string
	SnapshotID string
}

// APIV1TemplatesIDDeleteParams is parameters of DELETE /api/v1/templates/{id} operation.
type APIV1TemplatesIDDeleteParams struct {
	ID string
}

// APIV1TemplatesIDGetParams is parameters of GET /api/v1/templates/{id} operation.
type APIV1TemplatesIDGetParams struct {
	ID string
}

// APIV1TemplatesIDPutParams is parameters of PUT /api/v1/templates/{id} operation.
type APIV1TemplatesIDPutParams struct {
	ID string
}

// AuthOidcProviderCallbackGetParams is parameters of GET /auth/oidc/{provider}/callback operation.
type AuthOidcProviderCallbackGetParams struct {
	Provider string
	Code     string
	State    string
}

// AuthOidcProviderLoginGetParams is parameters of GET /auth/oidc/{provider}/login operation.
type AuthOidcProviderLoginGetParams struct {
	Provider  string
	ReturnURL OptString `json:",omitempty,omitzero"`
}

// TeamsIDDeleteParams is parameters of DELETE /teams/{id} operation.
type TeamsIDDeleteParams struct {
	ID string
}

// TeamsIDGetParams is parameters of GET /teams/{id} operation.
type TeamsIDGetParams struct {
	ID string
}

// TeamsIDMembersGetParams is parameters of GET /teams/{id}/members operation.
type TeamsIDMembersGetParams struct {
	ID string
}

// TeamsIDMembersPostParams is parameters of POST /teams/{id}/members operation.
type TeamsIDMembersPostParams struct {
	ID string
}

// TeamsIDMembersUserIdDeleteParams is parameters of DELETE /teams/{id}/members/{userId} operation.
type TeamsIDMembersUserIdDeleteParams struct {
	ID     string
	UserId string
}

// TeamsIDMembersUserIdPutParams is parameters of PUT /teams/{id}/members/{userId} operation.
type TeamsIDMembersUserIdPutParams struct {
	ID     string
	UserId string
}

// TeamsIDPutParams is parameters of PUT /teams/{id} operation.
type TeamsIDPutParams struct {
	ID string
}

// UsersMeIdentitiesIDDeleteParams is parameters of DELETE /users/me/identities/{id} operation.
type UsersMeIdentitiesIDDeleteParams struct {
	ID string
}
