// Code generated by ogen, DO NOT EDIT.

package apispec

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *APIKey) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Roles == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "roles",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *APIKeysIDDeactivatePostForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIKeysIDDeactivatePostNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIKeysIDDeleteForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIKeysIDDeleteNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIV1SandboxesIDDeleteForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIV1SandboxesIDDeleteNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIV1SandboxesIDGetForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIV1SandboxesIDGetNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIV1SandboxesIDPatchBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *APIV1SandboxesIDPatchNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AddTeamMemberRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         true,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Email)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "email",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Role.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "role",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddTeamMemberRequestRole) Validate() error {
	switch s {
	case "admin":
		return nil
	case "developer":
		return nil
	case "viewer":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AuthChangePasswordPostBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthChangePasswordPostUnauthorized) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthLoginPostBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthLoginPostForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthLoginPostUnauthorized) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthOidcProviderCallbackGetBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthOidcProviderCallbackGetUnauthorized) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthOidcProviderLoginGetBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthOidcProviderLoginGetNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthRefreshPostBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthRefreshPostUnauthorized) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthRegisterPostBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthRegisterPostConflict) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthRegisterPostForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ChangePasswordRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     8,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.NewPassword)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "new_password",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ClaimRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Config.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "config",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ContextResourceUsage) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Usage.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "usage",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ContextResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ContextStatsResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Usage.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "usage",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CreateAPIKeyRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateAPIKeyRequestType) Validate() error {
	switch s {
	case "user":
		return nil
	case "service":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateAPIKeyResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Roles == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "roles",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CreateContextRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Repl.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "repl",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CreateREPLContextRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.ReplConfig.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "repl_config",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CreateSandboxVolumeRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.AccessMode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "access_mode",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ErrorEnvelope) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ErrorEnvelopeSuccess) Validate() error {
	switch s {
	case false:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *FileContentResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Encoding.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "encoding",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s FileContentResponseEncoding) Validate() error {
	switch s {
	case "base64":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *FileInfo) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s FileInfoType) Validate() error {
	switch s {
	case "file":
		return nil
	case "dir":
		return nil
	case "symlink":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *LoginRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         true,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Email)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "email",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *LoginResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.User.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "user",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PauseSandboxResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.ResourceUsage.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "resource_usage",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ProcessType) Validate() error {
	switch s {
	case "repl":
		return nil
	case "cmd":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *REPLConfig) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Candidates == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "candidates",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Ready.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "ready",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *REPLReadyConfig) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Mode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "mode",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s REPLReadyMode) Validate() error {
	switch s {
	case "prompt_token":
		return nil
	case "startup_delay":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *RegisterRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         true,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Email)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "email",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     8,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Password)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "password",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ResourceUsage) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.CPUPercent.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "cpu_percent",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SandboxConfig) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Network.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "network",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SandboxResourceUsage) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Contexts {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "contexts",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SandboxTemplate) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Spec.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "spec",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SandboxTemplateSpec) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Network.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "network",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SandboxUpdateRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Config.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "config",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SandboxVolume) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.AccessMode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "access_mode",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SuccessAPIKeyListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SuccessAPIKeyListResponseData) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.APIKeys {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "api_keys",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessAPIKeyListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessAuthProvidersResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessAuthProvidersResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessClaimResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessClaimResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessContextExecResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessContextExecResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessContextListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SuccessContextListResponseData) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Contexts {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "contexts",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessContextListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessContextResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessContextResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessContextStatsResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessContextStatsResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessCreateAPIKeyResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessCreateAPIKeyResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessCreatedResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessCreatedResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessDeletedResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessDeletedResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessFileBinaryResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessFileBinaryResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessFileListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SuccessFileListResponseData) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Entries {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entries",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessFileListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessFileStatResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessFileStatResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessHealthResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessHealthResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessIdentityListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessIdentityListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessLoginResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessLoginResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessMessageResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessMessageResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessMountResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessMountResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessMountStatusResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessMountStatusResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessMovedResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessMovedResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessPauseSandboxResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessPauseSandboxResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessRefreshResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessRefreshResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessResizedResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessResizedResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessRestoreResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessRestoreResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessResumeSandboxResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessResumeSandboxResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSandboxNetworkPolicyResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSandboxNetworkPolicyResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSandboxResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSandboxResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSandboxStatusResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSandboxStatusResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSandboxVolumeListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Data {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSandboxVolumeListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSandboxVolumeResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSandboxVolumeResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSignaledResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSignaledResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSnapshotListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSnapshotListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessSnapshotResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessSnapshotResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessTeamListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessTeamListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessTeamMemberListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessTeamMemberListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessTeamMemberResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessTeamMemberResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessTeamResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessTeamResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessTemplateListResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SuccessTemplateListResponseData) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Templates {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "templates",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessTemplateListResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessTemplateResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessTemplateResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessUnmountedResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessUnmountedResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessUserResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Data.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessUserResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SuccessWrittenResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Success.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "success",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SuccessWrittenResponseSuccess) Validate() error {
	switch s {
	case true:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *TeamsIDDeleteForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDDeleteNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDGetForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDGetNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDMembersPostConflict) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDMembersPostForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDMembersPostNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDMembersUserIdDeleteForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDMembersUserIdDeleteNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDMembersUserIdPutForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDMembersUserIdPutNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDPutBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDPutForbidden) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsIDPutNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsPostBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TeamsPostConflict) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TplSandboxNetworkPolicy) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Mode.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "mode",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s TplSandboxNetworkPolicyMode) Validate() error {
	switch s {
	case "allow-all":
		return nil
	case "block-all":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *UpdateTeamMemberRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Role.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "role",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s UpdateTeamMemberRequestRole) Validate() error {
	switch s {
	case "admin":
		return nil
	case "developer":
		return nil
	case "viewer":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *User) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         true,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Email)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "email",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *UsersMeIdentitiesIDDeleteBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UsersMeIdentitiesIDDeleteNotFound) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UsersMeIdentitiesIDDeleteUnauthorized) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UsersMePutBadRequest) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UsersMePutUnauthorized) Validate() error {
	alias := (*ErrorEnvelope)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s VolumeAccessMode) Validate() error {
	switch s {
	case "RWO":
		return nil
	case "ROX":
		return nil
	case "RWX":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
