// Code generated by ogen, DO NOT EDIT.

package apispec

// setDefaults set default value of fields.
func (s *PoolStrategy) setDefaults() {
	{
		val := bool(false)
		s.AutoScale.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SandboxConfig) setDefaults() {
	{
		val := bool(true)
		s.AutoResume.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SandboxUpdateConfig) setDefaults() {
	{
		val := bool(true)
		s.AutoResume.SetTo(val)
	}
}
