// Code generated by ogen, DO NOT EDIT.
package apispec

type APIKeysCurrentGetRes interface {
	aPIKeysCurrentGetRes()
}

type APIKeysGetRes interface {
	aPIKeysGetRes()
}

type APIKeysIDDeactivatePostRes interface {
	aPIKeysIDDeactivatePostRes()
}

type APIKeysIDDeleteRes interface {
	aPIKeysIDDeleteRes()
}

type APIKeysPostRes interface {
	aPIKeysPostRes()
}

type APIV1CredentialSourcesNameGetRes interface {
	aPIV1CredentialSourcesNameGetRes()
}

type APIV1CredentialSourcesNamePutRes interface {
	aPIV1CredentialSourcesNamePutRes()
}

type APIV1CredentialSourcesPostRes interface {
	aPIV1CredentialSourcesPostRes()
}

type APIV1QuotasDimensionGetRes interface {
	aPIV1QuotasDimensionGetRes()
}

type APIV1RegistryCredentialsPostRes interface {
	aPIV1RegistryCredentialsPostRes()
}

type APIV1SandboxRootfsSnapshotsSnapshotIDDeleteRes interface {
	aPIV1SandboxRootfsSnapshotsSnapshotIDDeleteRes()
}

type APIV1SandboxRootfsSnapshotsSnapshotIDGetRes interface {
	aPIV1SandboxRootfsSnapshotsSnapshotIDGetRes()
}

type APIV1SandboxesGetRes interface {
	aPIV1SandboxesGetRes()
}

type APIV1SandboxesIDDeleteRes interface {
	aPIV1SandboxesIDDeleteRes()
}

type APIV1SandboxesIDFilesGetRes interface {
	aPIV1SandboxesIDFilesGetRes()
}

type APIV1SandboxesIDFilesPostRes interface {
	aPIV1SandboxesIDFilesPostRes()
}

type APIV1SandboxesIDForkPostRes interface {
	aPIV1SandboxesIDForkPostRes()
}

type APIV1SandboxesIDGetRes interface {
	aPIV1SandboxesIDGetRes()
}

type APIV1SandboxesIDNetworkGetRes interface {
	aPIV1SandboxesIDNetworkGetRes()
}

type APIV1SandboxesIDObservabilityEventsGetRes interface {
	aPIV1SandboxesIDObservabilityEventsGetRes()
}

type APIV1SandboxesIDObservabilityLogsGetRes interface {
	aPIV1SandboxesIDObservabilityLogsGetRes()
}

type APIV1SandboxesIDPausePostRes interface {
	aPIV1SandboxesIDPausePostRes()
}

type APIV1SandboxesIDPreviewsPostRes interface {
	aPIV1SandboxesIDPreviewsPostRes()
}

type APIV1SandboxesIDPreviewsPreviewIDDeleteRes interface {
	aPIV1SandboxesIDPreviewsPreviewIDDeleteRes()
}

type APIV1SandboxesIDPreviewsPreviewIDPutRes interface {
	aPIV1SandboxesIDPreviewsPreviewIDPutRes()
}

type APIV1SandboxesIDPutRes interface {
	aPIV1SandboxesIDPutRes()
}

type APIV1SandboxesIDRefreshPostRes interface {
	aPIV1SandboxesIDRefreshPostRes()
}

type APIV1SandboxesIDResumePostRes interface {
	aPIV1SandboxesIDResumePostRes()
}

type APIV1SandboxesIDRootfsRestorePostRes interface {
	aPIV1SandboxesIDRootfsRestorePostRes()
}

type APIV1SandboxesIDServicesGetRes interface {
	aPIV1SandboxesIDServicesGetRes()
}

type APIV1SandboxesIDServicesPutRes interface {
	aPIV1SandboxesIDServicesPutRes()
}

type APIV1SandboxesIDSessionsPostRes interface {
	aPIV1SandboxesIDSessionsPostRes()
}

type APIV1SandboxesIDSessionsSessionIDEventsGetRes interface {
	aPIV1SandboxesIDSessionsSessionIDEventsGetRes()
}

type APIV1SandboxesIDSnapshotsGetRes interface {
	aPIV1SandboxesIDSnapshotsGetRes()
}

type APIV1SandboxesIDSnapshotsPostRes interface {
	aPIV1SandboxesIDSnapshotsPostRes()
}

type APIV1SandboxesIDStatusGetRes interface {
	aPIV1SandboxesIDStatusGetRes()
}

type APIV1SandboxesPostRes interface {
	aPIV1SandboxesPostRes()
}

type APIV1SandboxvolumesIDDeleteRes interface {
	aPIV1SandboxvolumesIDDeleteRes()
}

type APIV1SandboxvolumesIDFilesGetRes interface {
	aPIV1SandboxvolumesIDFilesGetRes()
}

type APIV1SandboxvolumesIDFilesPostRes interface {
	aPIV1SandboxvolumesIDFilesPostRes()
}

type APIV1SandboxvolumesIDForkPostRes interface {
	aPIV1SandboxvolumesIDForkPostRes()
}

type APIV1SandboxvolumesIDGetRes interface {
	aPIV1SandboxvolumesIDGetRes()
}

type APIV1SandboxvolumesIDSnapshotsPostRes interface {
	aPIV1SandboxvolumesIDSnapshotsPostRes()
}

type APIV1SandboxvolumesIDSnapshotsSnapshotIDGetRes interface {
	aPIV1SandboxvolumesIDSnapshotsSnapshotIDGetRes()
}

type APIV1TemplatesFromSandboxPostRes interface {
	aPIV1TemplatesFromSandboxPostRes()
}

type APIV1TemplatesIDGetRes interface {
	aPIV1TemplatesIDGetRes()
}

type APIV1TemplatesIDPutRes interface {
	aPIV1TemplatesIDPutRes()
}

type APIV1UsageWindowsGetRes interface {
	aPIV1UsageWindowsGetRes()
}

type AuthChangePasswordPostRes interface {
	authChangePasswordPostRes()
}

type AuthLoginPostRes interface {
	authLoginPostRes()
}

type AuthOidcProviderCallbackGetRes interface {
	authOidcProviderCallbackGetRes()
}

type AuthOidcProviderDevicePollPostRes interface {
	authOidcProviderDevicePollPostRes()
}

type AuthOidcProviderDeviceStartPostRes interface {
	authOidcProviderDeviceStartPostRes()
}

type AuthOidcProviderLoginGetRes interface {
	authOidcProviderLoginGetRes()
}

type AuthProvidersGetRes interface {
	authProvidersGetRes()
}

type AuthRefreshPostRes interface {
	authRefreshPostRes()
}

type AuthRegisterPostRes interface {
	authRegisterPostRes()
}

type AuthWebLoginExchangePostRes interface {
	authWebLoginExchangePostRes()
}

type GetSandboxRuntimeMetricsCatalogRes interface {
	getSandboxRuntimeMetricsCatalogRes()
}

type GetSandboxRuntimeMetricsRes interface {
	getSandboxRuntimeMetricsRes()
}

type HealthzGetRes interface {
	healthzGetRes()
}

type ReadyzGetRes interface {
	readyzGetRes()
}

type RegionsGetRes interface {
	regionsGetRes()
}

type RegionsIDDeleteRes interface {
	regionsIDDeleteRes()
}

type RegionsIDGetRes interface {
	regionsIDGetRes()
}

type RegionsIDPutRes interface {
	regionsIDPutRes()
}

type RegionsPostRes interface {
	regionsPostRes()
}

type TeamsGetRes interface {
	teamsGetRes()
}

type TeamsIDDeleteRes interface {
	teamsIDDeleteRes()
}

type TeamsIDGetRes interface {
	teamsIDGetRes()
}

type TeamsIDMembersGetRes interface {
	teamsIDMembersGetRes()
}

type TeamsIDMembersPostRes interface {
	teamsIDMembersPostRes()
}

type TeamsIDMembersUserIdDeleteRes interface {
	teamsIDMembersUserIdDeleteRes()
}

type TeamsIDMembersUserIdPutRes interface {
	teamsIDMembersUserIdPutRes()
}

type TeamsIDOwnerPutRes interface {
	teamsIDOwnerPutRes()
}

type TeamsIDPutRes interface {
	teamsIDPutRes()
}

type TeamsPostRes interface {
	teamsPostRes()
}

type UsersMeGetRes interface {
	usersMeGetRes()
}

type UsersMeIdentitiesGetRes interface {
	usersMeIdentitiesGetRes()
}

type UsersMeIdentitiesIDDeleteRes interface {
	usersMeIdentitiesIDDeleteRes()
}

type UsersMePutRes interface {
	usersMePutRes()
}

type UsersMeSSHKeysGetRes interface {
	usersMeSSHKeysGetRes()
}

type UsersMeSSHKeysIDDeleteRes interface {
	usersMeSSHKeysIDDeleteRes()
}

type UsersMeSSHKeysPostRes interface {
	usersMeSSHKeysPostRes()
}
