// Code generated by ogen, DO NOT EDIT.

package apispec

import (
	"context"
	"net/http"

	ht "github.com/ogen-go/ogen/http"
)

type (
	optionFunc[C any] func(*C)
)

type clientConfig struct {
	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditor
	// A list of callbacks for modifying response.
	ResponseEditors []ResponseEditor
	Client          ht.Client
}

// ClientOption is client config option.
type ClientOption interface {
	applyClient(*clientConfig)
}

var _ ClientOption = (optionFunc[clientConfig])(nil)

func (o optionFunc[C]) applyClient(c *C) {
	o(c)
}

func newClientConfig(opts ...ClientOption) clientConfig {
	cfg := clientConfig{
		Client: http.DefaultClient,
	}
	for _, opt := range opts {
		opt.applyClient(&cfg)
	}
	return cfg
}

type baseClient struct {
	cfg clientConfig
}

func (cfg clientConfig) baseClient() (c baseClient, err error) {
	c = baseClient{cfg: cfg}
	return c, nil
}

// Option is config option.
type Option interface {
	ClientOption
}

// WithClient specifies http client to use.
func WithClient(client ht.Client) ClientOption {
	return optionFunc[clientConfig](func(cfg *clientConfig) {
		if client != nil {
			cfg.Client = client
		}
	})
}

// RequestEditor is the function signature for the RequestEditor callback function
type RequestEditor func(ctx context.Context, req *http.Request) error

// ResponseEditor is the function signature for the ResponseEditor callback function
type ResponseEditor func(ctx context.Context, resp *http.Response) error

// WithRequestEditor allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditor(fn RequestEditor) ClientOption {
	return optionFunc[clientConfig](func(cfg *clientConfig) {
		cfg.RequestEditors = append(cfg.RequestEditors, fn)
	})
}

// WithResponseEditor allows setting up a callback function, which will be
// called right after receiving the response. This can be used to mutate the response.
func WithResponseEditor(fn ResponseEditor) ClientOption {
	return optionFunc[clientConfig](func(cfg *clientConfig) {
		cfg.ResponseEditors = append(cfg.ResponseEditors, fn)
	})
}
