// Code generated by ogen, DO NOT EDIT.

package apispec

// APIKeysIDDeactivatePostParams is parameters of POST /api-keys/{id}/deactivate operation.
type APIKeysIDDeactivatePostParams struct {
	ID string
}

// APIKeysIDDeleteParams is parameters of DELETE /api-keys/{id} operation.
type APIKeysIDDeleteParams struct {
	ID string
}

// APIV1CredentialSourcesNameDeleteParams is parameters of DELETE /api/v1/credential-sources/{name} operation.
type APIV1CredentialSourcesNameDeleteParams struct {
	Name string
}

// APIV1CredentialSourcesNameGetParams is parameters of GET /api/v1/credential-sources/{name} operation.
type APIV1CredentialSourcesNameGetParams struct {
	Name string
}

// APIV1CredentialSourcesNamePutParams is parameters of PUT /api/v1/credential-sources/{name} operation.
type APIV1CredentialSourcesNamePutParams struct {
	Name string
}

// APIV1SandboxRootfsSnapshotsSnapshotIDDeleteParams is parameters of DELETE /api/v1/sandbox-rootfs-snapshots/{snapshot_id} operation.
type APIV1SandboxRootfsSnapshotsSnapshotIDDeleteParams struct {
	SnapshotID string
}

// APIV1SandboxRootfsSnapshotsSnapshotIDGetParams is parameters of GET /api/v1/sandbox-rootfs-snapshots/{snapshot_id} operation.
type APIV1SandboxRootfsSnapshotsSnapshotIDGetParams struct {
	SnapshotID string
}

// APIV1SandboxesGetParams is parameters of GET /api/v1/sandboxes operation.
type APIV1SandboxesGetParams struct {
	// Filter by sandbox status.
	Status OptSandboxLifecycleStatus `json:",omitempty,omitzero"`
	// Filter by template ID.
	TemplateID OptString `json:",omitempty,omitzero"`
	// Filter by paused state.
	Paused OptBool `json:",omitempty,omitzero"`
	// Maximum number of results per page.
	Limit OptInt `json:",omitempty,omitzero"`
	// Pagination offset.
	Offset OptInt `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDContextsCtxIDDeleteParams is parameters of DELETE /api/v1/sandboxes/{id}/contexts/{ctx_id} operation.
type APIV1SandboxesIDContextsCtxIDDeleteParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDExecPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/exec operation.
type APIV1SandboxesIDContextsCtxIDExecPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDGetParams is parameters of GET /api/v1/sandboxes/{id}/contexts/{ctx_id} operation.
type APIV1SandboxesIDContextsCtxIDGetParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDInputPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/input operation.
type APIV1SandboxesIDContextsCtxIDInputPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDResizePostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/resize operation.
type APIV1SandboxesIDContextsCtxIDResizePostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDRestartPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/restart operation.
type APIV1SandboxesIDContextsCtxIDRestartPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDSignalPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts/{ctx_id}/signal operation.
type APIV1SandboxesIDContextsCtxIDSignalPostParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsCtxIDWsGetParams is parameters of GET /api/v1/sandboxes/{id}/contexts/{ctx_id}/ws operation.
type APIV1SandboxesIDContextsCtxIDWsGetParams struct {
	ID    string
	CtxID string
}

// APIV1SandboxesIDContextsGetParams is parameters of GET /api/v1/sandboxes/{id}/contexts operation.
type APIV1SandboxesIDContextsGetParams struct {
	ID string
}

// APIV1SandboxesIDContextsPostParams is parameters of POST /api/v1/sandboxes/{id}/contexts operation.
type APIV1SandboxesIDContextsPostParams struct {
	ID string
}

// APIV1SandboxesIDDeleteParams is parameters of DELETE /api/v1/sandboxes/{id} operation.
type APIV1SandboxesIDDeleteParams struct {
	ID string
}

// APIV1SandboxesIDFilesDeleteParams is parameters of DELETE /api/v1/sandboxes/{id}/files operation.
type APIV1SandboxesIDFilesDeleteParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesGetParams is parameters of GET /api/v1/sandboxes/{id}/files operation.
type APIV1SandboxesIDFilesGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesListGetParams is parameters of GET /api/v1/sandboxes/{id}/files/list operation.
type APIV1SandboxesIDFilesListGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesMovePostParams is parameters of POST /api/v1/sandboxes/{id}/files/move operation.
type APIV1SandboxesIDFilesMovePostParams struct {
	ID string
}

// APIV1SandboxesIDFilesPostParams is parameters of POST /api/v1/sandboxes/{id}/files operation.
type APIV1SandboxesIDFilesPostParams struct {
	ID        string
	Path      string
	Mkdir     OptBool `json:",omitempty,omitzero"`
	Recursive OptBool `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDFilesStatGetParams is parameters of GET /api/v1/sandboxes/{id}/files/stat operation.
type APIV1SandboxesIDFilesStatGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxesIDFilesWatchGetParams is parameters of GET /api/v1/sandboxes/{id}/files/watch operation.
type APIV1SandboxesIDFilesWatchGetParams struct {
	ID string
}

// APIV1SandboxesIDForkPostParams is parameters of POST /api/v1/sandboxes/{id}/fork operation.
type APIV1SandboxesIDForkPostParams struct {
	ID string
}

// APIV1SandboxesIDGetParams is parameters of GET /api/v1/sandboxes/{id} operation.
type APIV1SandboxesIDGetParams struct {
	ID string
}

// APIV1SandboxesIDNetworkGetParams is parameters of GET /api/v1/sandboxes/{id}/network operation.
type APIV1SandboxesIDNetworkGetParams struct {
	ID string
}

// APIV1SandboxesIDNetworkPutParams is parameters of PUT /api/v1/sandboxes/{id}/network operation.
type APIV1SandboxesIDNetworkPutParams struct {
	ID string
}

// APIV1SandboxesIDObservabilityEventsGetParams is parameters of GET /api/v1/sandboxes/{id}/observability/events operation.
type APIV1SandboxesIDObservabilityEventsGetParams struct {
	ID string
	// Include events that occurred at or after this RFC3339 timestamp.
	StartTime OptDateTime `json:",omitempty,omitzero"`
	// Include events that occurred at or before this RFC3339 timestamp.
	EndTime OptDateTime `json:",omitempty,omitzero"`
	// Maximum number of events to return. Values above 1000 are capped. Exact event_id mode ignores this
	// value and returns at most two payload variants.
	Limit OptInt `json:",omitempty,omitzero"`
	// Opaque pagination cursor returned by a previous response. When watch is true, this must be a watch
	// resume cursor from an NDJSON watermark line.
	Cursor OptString `json:",omitempty,omitzero"`
	// Stream matching records as application/x-ndjson in ingestion order until the client disconnects.
	// When watch is true, end_time is not supported. Without cursor or start_time, streaming starts at
	// request time.
	Watch        OptBool                          `json:",omitempty,omitzero"`
	Source       OptObservabilityEventSource      `json:",omitempty,omitzero"`
	EventType    OptSandboxObservabilityEventType `json:",omitempty,omitzero"`
	Outcome      OptSandboxObservabilityOutcome   `json:",omitempty,omitzero"`
	ActorKind    OptSandboxAuditActorKind         `json:",omitempty,omitzero"`
	ActorID      OptString                        `json:",omitempty,omitzero"`
	Action       OptString                        `json:",omitempty,omitzero"`
	ResourceType OptString                        `json:",omitempty,omitzero"`
	OperationID  OptString                        `json:",omitempty,omitzero"`
	// Exact lookup mode for one stable audit event ID. It cannot be combined with time, cursor, watch,
	// or other event filters and returns one canonical row or two conflicting payload variants.
	EventID OptUUID `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDObservabilityLogsGetParams is parameters of GET /api/v1/sandboxes/{id}/observability/logs operation.
type APIV1SandboxesIDObservabilityLogsGetParams struct {
	ID string
	// Include log entries that occurred at or after this RFC3339 timestamp.
	StartTime OptDateTime `json:",omitempty,omitzero"`
	// Include log entries that occurred at or before this RFC3339 timestamp.
	EndTime OptDateTime `json:",omitempty,omitzero"`
	// Maximum number of log entries to return. Values above 1000 are capped.
	Limit OptInt `json:",omitempty,omitzero"`
	// Opaque pagination cursor returned by a previous response. When watch is true, this must be a watch
	// resume cursor from an NDJSON watermark line.
	Cursor OptString `json:",omitempty,omitzero"`
	// Stream matching records as application/x-ndjson in ingestion order until the client disconnects.
	// When watch is true, end_time is not supported. Without cursor or start_time, streaming starts at
	// request time.
	Watch OptBool `json:",omitempty,omitzero"`
	// Restrict results to a sandbox process context.
	ContextID OptString                        `json:",omitempty,omitzero"`
	Stream    OptSandboxObservabilityLogStream `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDPausePostParams is parameters of POST /api/v1/sandboxes/{id}/pause operation.
type APIV1SandboxesIDPausePostParams struct {
	ID string
}

// APIV1SandboxesIDPutParams is parameters of PUT /api/v1/sandboxes/{id} operation.
type APIV1SandboxesIDPutParams struct {
	ID string
}

// APIV1SandboxesIDRefreshPostParams is parameters of POST /api/v1/sandboxes/{id}/refresh operation.
type APIV1SandboxesIDRefreshPostParams struct {
	ID string
}

// APIV1SandboxesIDResumePostParams is parameters of POST /api/v1/sandboxes/{id}/resume operation.
type APIV1SandboxesIDResumePostParams struct {
	ID string
}

// APIV1SandboxesIDRootfsRestorePostParams is parameters of POST /api/v1/sandboxes/{id}/rootfs/restore operation.
type APIV1SandboxesIDRootfsRestorePostParams struct {
	ID string
}

// APIV1SandboxesIDServicesGetParams is parameters of GET /api/v1/sandboxes/{id}/services operation.
type APIV1SandboxesIDServicesGetParams struct {
	ID string
}

// APIV1SandboxesIDServicesPutParams is parameters of PUT /api/v1/sandboxes/{id}/services operation.
type APIV1SandboxesIDServicesPutParams struct {
	ID string
}

// APIV1SandboxesIDSessionsGetParams is parameters of GET /api/v1/sandboxes/{id}/sessions operation.
type APIV1SandboxesIDSessionsGetParams struct {
	ID string
}

// APIV1SandboxesIDSessionsPostParams is parameters of POST /api/v1/sandboxes/{id}/sessions operation.
type APIV1SandboxesIDSessionsPostParams struct {
	ID string
	// Optional key for retrying creation without creating a duplicate session.
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDSessionsSessionIDAttemptsPostParams is parameters of POST /api/v1/sandboxes/{id}/sessions/{session_id}/attempts operation.
type APIV1SandboxesIDSessionsSessionIDAttemptsPostParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDDeleteParams is parameters of DELETE /api/v1/sandboxes/{id}/sessions/{session_id} operation.
type APIV1SandboxesIDSessionsSessionIDDeleteParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDDesiredStatePutParams is parameters of PUT /api/v1/sandboxes/{id}/sessions/{session_id}/desired-state operation.
type APIV1SandboxesIDSessionsSessionIDDesiredStatePutParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDEventsGetParams is parameters of GET /api/v1/sandboxes/{id}/sessions/{session_id}/events operation.
type APIV1SandboxesIDSessionsSessionIDEventsGetParams struct {
	ID        string
	SessionID string
	After     OptInt64 `json:",omitempty,omitzero"`
	Limit     OptInt   `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDSessionsSessionIDEventsStreamGetParams is parameters of GET /api/v1/sandboxes/{id}/sessions/{session_id}/events/stream operation.
type APIV1SandboxesIDSessionsSessionIDEventsStreamGetParams struct {
	ID          string
	SessionID   string
	After       OptInt64  `json:",omitempty,omitzero"`
	LastEventID OptString `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDSessionsSessionIDGetParams is parameters of GET /api/v1/sandboxes/{id}/sessions/{session_id} operation.
type APIV1SandboxesIDSessionsSessionIDGetParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDInputsPostParams is parameters of POST /api/v1/sandboxes/{id}/sessions/{session_id}/inputs operation.
type APIV1SandboxesIDSessionsSessionIDInputsPostParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDPutParams is parameters of PUT /api/v1/sandboxes/{id}/sessions/{session_id} operation.
type APIV1SandboxesIDSessionsSessionIDPutParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDSignalsPostParams is parameters of POST /api/v1/sandboxes/{id}/sessions/{session_id}/signals operation.
type APIV1SandboxesIDSessionsSessionIDSignalsPostParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDTerminalPutParams is parameters of PUT /api/v1/sandboxes/{id}/sessions/{session_id}/terminal operation.
type APIV1SandboxesIDSessionsSessionIDTerminalPutParams struct {
	ID        string
	SessionID string
}

// APIV1SandboxesIDSessionsSessionIDWsGetParams is parameters of GET /api/v1/sandboxes/{id}/sessions/{session_id}/ws operation.
type APIV1SandboxesIDSessionsSessionIDWsGetParams struct {
	ID        string
	SessionID string
	After     OptInt64 `json:",omitempty,omitzero"`
}

// APIV1SandboxesIDSnapshotsGetParams is parameters of GET /api/v1/sandboxes/{id}/snapshots operation.
type APIV1SandboxesIDSnapshotsGetParams struct {
	ID string
}

// APIV1SandboxesIDSnapshotsPostParams is parameters of POST /api/v1/sandboxes/{id}/snapshots operation.
type APIV1SandboxesIDSnapshotsPostParams struct {
	ID string
}

// APIV1SandboxesIDStatusGetParams is parameters of GET /api/v1/sandboxes/{id}/status operation.
type APIV1SandboxesIDStatusGetParams struct {
	ID string
}

// APIV1SandboxvolumesIDDeleteParams is parameters of DELETE /api/v1/sandboxvolumes/{id} operation.
type APIV1SandboxvolumesIDDeleteParams struct {
	ID string
	// Force delete even if volume has active mounts.
	Force OptBool `json:",omitempty,omitzero"`
}

// APIV1SandboxvolumesIDFilesArchivePutParams is parameters of PUT /api/v1/sandboxvolumes/{id}/files/archive operation.
type APIV1SandboxvolumesIDFilesArchivePutParams struct {
	ID   string
	Path string
}

// APIV1SandboxvolumesIDFilesDeleteParams is parameters of DELETE /api/v1/sandboxvolumes/{id}/files operation.
type APIV1SandboxvolumesIDFilesDeleteParams struct {
	ID   string
	Path string
}

// APIV1SandboxvolumesIDFilesGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/files operation.
type APIV1SandboxvolumesIDFilesGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxvolumesIDFilesListGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/files/list operation.
type APIV1SandboxvolumesIDFilesListGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxvolumesIDFilesMovePostParams is parameters of POST /api/v1/sandboxvolumes/{id}/files/move operation.
type APIV1SandboxvolumesIDFilesMovePostParams struct {
	ID string
}

// APIV1SandboxvolumesIDFilesPostParams is parameters of POST /api/v1/sandboxvolumes/{id}/files operation.
type APIV1SandboxvolumesIDFilesPostParams struct {
	ID        string
	Path      string
	Mkdir     OptBool `json:",omitempty,omitzero"`
	Recursive OptBool `json:",omitempty,omitzero"`
}

// APIV1SandboxvolumesIDFilesStatGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/files/stat operation.
type APIV1SandboxvolumesIDFilesStatGetParams struct {
	ID   string
	Path string
}

// APIV1SandboxvolumesIDFilesWatchGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/files/watch operation.
type APIV1SandboxvolumesIDFilesWatchGetParams struct {
	ID string
}

// APIV1SandboxvolumesIDForkPostParams is parameters of POST /api/v1/sandboxvolumes/{id}/fork operation.
type APIV1SandboxvolumesIDForkPostParams struct {
	ID string
}

// APIV1SandboxvolumesIDGetParams is parameters of GET /api/v1/sandboxvolumes/{id} operation.
type APIV1SandboxvolumesIDGetParams struct {
	ID string
}

// APIV1SandboxvolumesIDSnapshotsGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/snapshots operation.
type APIV1SandboxvolumesIDSnapshotsGetParams struct {
	ID string
}

// APIV1SandboxvolumesIDSnapshotsPostParams is parameters of POST /api/v1/sandboxvolumes/{id}/snapshots operation.
type APIV1SandboxvolumesIDSnapshotsPostParams struct {
	ID string
}

// APIV1SandboxvolumesIDSnapshotsSnapshotIDDeleteParams is parameters of DELETE /api/v1/sandboxvolumes/{id}/snapshots/{snapshot_id} operation.
type APIV1SandboxvolumesIDSnapshotsSnapshotIDDeleteParams struct {
	ID         string
	SnapshotID string
}

// APIV1SandboxvolumesIDSnapshotsSnapshotIDGetParams is parameters of GET /api/v1/sandboxvolumes/{id}/snapshots/{snapshot_id} operation.
type APIV1SandboxvolumesIDSnapshotsSnapshotIDGetParams struct {
	ID         string
	SnapshotID string
}

// APIV1SandboxvolumesIDSnapshotsSnapshotIDRestorePostParams is parameters of POST /api/v1/sandboxvolumes/{id}/snapshots/{snapshot_id}/restore operation.
type APIV1SandboxvolumesIDSnapshotsSnapshotIDRestorePostParams struct {
	ID         string
	SnapshotID string
}

// APIV1TeamsTeamIDQuotasGetParams is parameters of GET /api/v1/teams/{team_id}/quotas operation.
type APIV1TeamsTeamIDQuotasGetParams struct {
	TeamID string
}

// APIV1TeamsTeamIDQuotasKeyDeleteParams is parameters of DELETE /api/v1/teams/{team_id}/quotas/{key} operation.
type APIV1TeamsTeamIDQuotasKeyDeleteParams struct {
	TeamID string
	Key    TeamQuotaKey
}

// APIV1TeamsTeamIDQuotasKeyPutParams is parameters of PUT /api/v1/teams/{team_id}/quotas/{key} operation.
type APIV1TeamsTeamIDQuotasKeyPutParams struct {
	TeamID string
	Key    TeamQuotaKey
}

// APIV1TemplatesFromSandboxPostParams is parameters of POST /api/v1/templates/from-sandbox operation.
type APIV1TemplatesFromSandboxPostParams struct {
	// Optional key for retrying creation without starting a duplicate image build.
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// APIV1TemplatesIDDeleteParams is parameters of DELETE /api/v1/templates/{id} operation.
type APIV1TemplatesIDDeleteParams struct {
	ID string
}

// APIV1TemplatesIDGetParams is parameters of GET /api/v1/templates/{id} operation.
type APIV1TemplatesIDGetParams struct {
	ID string
}

// APIV1TemplatesIDPutParams is parameters of PUT /api/v1/templates/{id} operation.
type APIV1TemplatesIDPutParams struct {
	ID string
}

// AuthOidcProviderCallbackGetParams is parameters of GET /auth/oidc/{provider}/callback operation.
type AuthOidcProviderCallbackGetParams struct {
	Provider string
	Code     string
	State    string
}

// AuthOidcProviderDevicePollPostParams is parameters of POST /auth/oidc/{provider}/device/poll operation.
type AuthOidcProviderDevicePollPostParams struct {
	Provider string
}

// AuthOidcProviderDeviceStartPostParams is parameters of POST /auth/oidc/{provider}/device/start operation.
type AuthOidcProviderDeviceStartPostParams struct {
	Provider string
}

// AuthOidcProviderLoginGetParams is parameters of GET /auth/oidc/{provider}/login operation.
type AuthOidcProviderLoginGetParams struct {
	Provider  string
	ReturnURL OptString `json:",omitempty,omitzero"`
	// When true, the OIDC callback redirects to return_url with a short-lived login_code for server-side
	// exchange.
	WebLogin OptBool `json:",omitempty,omitzero"`
}

// AuthOidcProviderLogoutGetParams is parameters of GET /auth/oidc/{provider}/logout operation.
type AuthOidcProviderLogoutGetParams struct {
	Provider string
	// URL to return to after the identity provider completes logout.
	ReturnURL OptString `json:",omitempty,omitzero"`
}

// GetSandboxRuntimeMetricsParams is parameters of getSandboxRuntimeMetrics operation.
type GetSandboxRuntimeMetricsParams struct {
	ID string
	// Query observations at or after this RFC3339 timestamp. Defaults to one hour before end_time.
	StartTime OptDateTime `json:",omitempty,omitzero"`
	// Query observations at or before this RFC3339 timestamp. Defaults to the current time.
	EndTime OptDateTime `json:",omitempty,omitzero"`
	// Comma-separated canonical metric names. Defaults to CPU utilization, memory utilization, and
	// network I/O.
	Metrics OptString `json:",omitempty,omitzero"`
	// Requested bucket width in seconds. The effective step is at least 15 seconds and may be increased
	// to honor max_points.
	StepSeconds OptInt `json:",omitempty,omitzero"`
	// Aggregation applied within each output bucket. Auto uses average for gauges and rate for counters.
	Statistic OptSandboxRuntimeMetricStatistic `json:",omitempty,omitzero"`
	// Maximum points per returned series. The server may increase step_seconds to honor this bound.
	MaxPoints OptInt `json:",omitempty,omitzero"`
}

// GetSandboxRuntimeMetricsCatalogParams is parameters of getSandboxRuntimeMetricsCatalog operation.
type GetSandboxRuntimeMetricsCatalogParams struct {
	ID string
}

// RegionsIDDeleteParams is parameters of DELETE /regions/{id} operation.
type RegionsIDDeleteParams struct {
	ID string
}

// RegionsIDGetParams is parameters of GET /regions/{id} operation.
type RegionsIDGetParams struct {
	ID string
}

// RegionsIDPutParams is parameters of PUT /regions/{id} operation.
type RegionsIDPutParams struct {
	ID string
}

// TeamsIDDeleteParams is parameters of DELETE /teams/{id} operation.
type TeamsIDDeleteParams struct {
	ID string
}

// TeamsIDGetParams is parameters of GET /teams/{id} operation.
type TeamsIDGetParams struct {
	ID string
}

// TeamsIDMembersGetParams is parameters of GET /teams/{id}/members operation.
type TeamsIDMembersGetParams struct {
	ID string
	// Search by member email, display name, or user ID.
	Query OptString `json:",omitempty,omitzero"`
}

// TeamsIDMembersPostParams is parameters of POST /teams/{id}/members operation.
type TeamsIDMembersPostParams struct {
	ID string
}

// TeamsIDMembersUserIdDeleteParams is parameters of DELETE /teams/{id}/members/{userId} operation.
type TeamsIDMembersUserIdDeleteParams struct {
	ID     string
	UserId string
}

// TeamsIDMembersUserIdPutParams is parameters of PUT /teams/{id}/members/{userId} operation.
type TeamsIDMembersUserIdPutParams struct {
	ID     string
	UserId string
}

// TeamsIDOwnerPutParams is parameters of PUT /teams/{id}/owner operation.
type TeamsIDOwnerPutParams struct {
	ID string
}

// TeamsIDPutParams is parameters of PUT /teams/{id} operation.
type TeamsIDPutParams struct {
	ID string
}

// UsersMeIdentitiesIDDeleteParams is parameters of DELETE /users/me/identities/{id} operation.
type UsersMeIdentitiesIDDeleteParams struct {
	ID string
}

// UsersMeSSHKeysIDDeleteParams is parameters of DELETE /users/me/ssh-keys/{id} operation.
type UsersMeSSHKeysIDDeleteParams struct {
	ID string
}
