// Code generated by ogen, DO NOT EDIT.
package apispec

type APIKeysGetRes interface {
	aPIKeysGetRes()
}

type APIKeysIDDeactivatePostRes interface {
	aPIKeysIDDeactivatePostRes()
}

type APIKeysIDDeleteRes interface {
	aPIKeysIDDeleteRes()
}

type APIKeysPostRes interface {
	aPIKeysPostRes()
}

type APIV1RegistryCredentialsPostRes interface {
	aPIV1RegistryCredentialsPostRes()
}

type APIV1SandboxesIDDeleteRes interface {
	aPIV1SandboxesIDDeleteRes()
}

type APIV1SandboxesIDFilesGetRes interface {
	aPIV1SandboxesIDFilesGetRes()
}

type APIV1SandboxesIDFilesPostRes interface {
	aPIV1SandboxesIDFilesPostRes()
}

type APIV1SandboxesIDGetRes interface {
	aPIV1SandboxesIDGetRes()
}

type APIV1SandboxesIDNetworkGetRes interface {
	aPIV1SandboxesIDNetworkGetRes()
}

type APIV1SandboxesIDPausePostRes interface {
	aPIV1SandboxesIDPausePostRes()
}

type APIV1SandboxesIDPutRes interface {
	aPIV1SandboxesIDPutRes()
}

type APIV1SandboxesIDRefreshPostRes interface {
	aPIV1SandboxesIDRefreshPostRes()
}

type APIV1SandboxesIDResumePostRes interface {
	aPIV1SandboxesIDResumePostRes()
}

type APIV1SandboxesIDStatusGetRes interface {
	aPIV1SandboxesIDStatusGetRes()
}

type APIV1SandboxesPostRes interface {
	aPIV1SandboxesPostRes()
}

type APIV1SandboxvolumesIDDeleteRes interface {
	aPIV1SandboxvolumesIDDeleteRes()
}

type APIV1SandboxvolumesIDGetRes interface {
	aPIV1SandboxvolumesIDGetRes()
}

type APIV1SandboxvolumesIDSnapshotsSnapshotIDGetRes interface {
	aPIV1SandboxvolumesIDSnapshotsSnapshotIDGetRes()
}

type APIV1TemplatesIDGetRes interface {
	aPIV1TemplatesIDGetRes()
}

type AuthChangePasswordPostRes interface {
	authChangePasswordPostRes()
}

type AuthLoginPostRes interface {
	authLoginPostRes()
}

type AuthOidcProviderCallbackGetRes interface {
	authOidcProviderCallbackGetRes()
}

type AuthOidcProviderLoginGetRes interface {
	authOidcProviderLoginGetRes()
}

type AuthProvidersGetRes interface {
	authProvidersGetRes()
}

type AuthRefreshPostRes interface {
	authRefreshPostRes()
}

type AuthRegisterPostRes interface {
	authRegisterPostRes()
}

type HealthzGetRes interface {
	healthzGetRes()
}

type ReadyzGetRes interface {
	readyzGetRes()
}

type TeamsGetRes interface {
	teamsGetRes()
}

type TeamsIDDeleteRes interface {
	teamsIDDeleteRes()
}

type TeamsIDGetRes interface {
	teamsIDGetRes()
}

type TeamsIDMembersGetRes interface {
	teamsIDMembersGetRes()
}

type TeamsIDMembersPostRes interface {
	teamsIDMembersPostRes()
}

type TeamsIDMembersUserIdDeleteRes interface {
	teamsIDMembersUserIdDeleteRes()
}

type TeamsIDMembersUserIdPutRes interface {
	teamsIDMembersUserIdPutRes()
}

type TeamsIDPutRes interface {
	teamsIDPutRes()
}

type TeamsPostRes interface {
	teamsPostRes()
}

type UsersMeGetRes interface {
	usersMeGetRes()
}

type UsersMeIdentitiesGetRes interface {
	usersMeIdentitiesGetRes()
}

type UsersMeIdentitiesIDDeleteRes interface {
	usersMeIdentitiesIDDeleteRes()
}

type UsersMePutRes interface {
	usersMePutRes()
}
