// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apispec

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AddTeamMemberRequestRole.
const (
	AddTeamMemberRequestRoleAdmin     AddTeamMemberRequestRole = "admin"
	AddTeamMemberRequestRoleDeveloper AddTeamMemberRequestRole = "developer"
	AddTeamMemberRequestRoleViewer    AddTeamMemberRequestRole = "viewer"
)

// Defines values for CreateAPIKeyRequestType.
const (
	CreateAPIKeyRequestTypeService CreateAPIKeyRequestType = "service"
	CreateAPIKeyRequestTypeUser    CreateAPIKeyRequestType = "user"
)

// Defines values for ErrorEnvelopeSuccess.
const (
	False ErrorEnvelopeSuccess = false
)

// Defines values for FileContentResponseEncoding.
const (
	Base64 FileContentResponseEncoding = "base64"
)

// Defines values for FileInfoType.
const (
	Dir     FileInfoType = "dir"
	File    FileInfoType = "file"
	Symlink FileInfoType = "symlink"
)

// Defines values for ProcessType.
const (
	Cmd  ProcessType = "cmd"
	Repl ProcessType = "repl"
)

// Defines values for REPLReadyMode.
const (
	PromptToken  REPLReadyMode = "prompt_token"
	StartupDelay REPLReadyMode = "startup_delay"
)

// Defines values for SuccessAPIKeyListResponseSuccess.
const (
	SuccessAPIKeyListResponseSuccessTrue SuccessAPIKeyListResponseSuccess = true
)

// Defines values for SuccessAuthProvidersResponseSuccess.
const (
	SuccessAuthProvidersResponseSuccessTrue SuccessAuthProvidersResponseSuccess = true
)

// Defines values for SuccessBandwidthPolicyResponseSuccess.
const (
	SuccessBandwidthPolicyResponseSuccessTrue SuccessBandwidthPolicyResponseSuccess = true
)

// Defines values for SuccessClaimResponseSuccess.
const (
	SuccessClaimResponseSuccessTrue SuccessClaimResponseSuccess = true
)

// Defines values for SuccessContextExecResponseSuccess.
const (
	SuccessContextExecResponseSuccessTrue SuccessContextExecResponseSuccess = true
)

// Defines values for SuccessContextListResponseSuccess.
const (
	SuccessContextListResponseSuccessTrue SuccessContextListResponseSuccess = true
)

// Defines values for SuccessContextResponseSuccess.
const (
	SuccessContextResponseSuccessTrue SuccessContextResponseSuccess = true
)

// Defines values for SuccessContextStatsResponseSuccess.
const (
	SuccessContextStatsResponseSuccessTrue SuccessContextStatsResponseSuccess = true
)

// Defines values for SuccessCreateAPIKeyResponseSuccess.
const (
	SuccessCreateAPIKeyResponseSuccessTrue SuccessCreateAPIKeyResponseSuccess = true
)

// Defines values for SuccessCreatedResponseSuccess.
const (
	SuccessCreatedResponseSuccessTrue SuccessCreatedResponseSuccess = true
)

// Defines values for SuccessDeletedResponseSuccess.
const (
	SuccessDeletedResponseSuccessTrue SuccessDeletedResponseSuccess = true
)

// Defines values for SuccessEnvelopeSuccess.
const (
	SuccessEnvelopeSuccessTrue SuccessEnvelopeSuccess = true
)

// Defines values for SuccessFileBinaryResponseSuccess.
const (
	SuccessFileBinaryResponseSuccessTrue SuccessFileBinaryResponseSuccess = true
)

// Defines values for SuccessFileListResponseSuccess.
const (
	SuccessFileListResponseSuccessTrue SuccessFileListResponseSuccess = true
)

// Defines values for SuccessFileStatResponseSuccess.
const (
	SuccessFileStatResponseSuccessTrue SuccessFileStatResponseSuccess = true
)

// Defines values for SuccessHealthResponseSuccess.
const (
	SuccessHealthResponseSuccessTrue SuccessHealthResponseSuccess = true
)

// Defines values for SuccessIdentityListResponseSuccess.
const (
	SuccessIdentityListResponseSuccessTrue SuccessIdentityListResponseSuccess = true
)

// Defines values for SuccessLoginResponseSuccess.
const (
	SuccessLoginResponseSuccessTrue SuccessLoginResponseSuccess = true
)

// Defines values for SuccessMessageResponseSuccess.
const (
	SuccessMessageResponseSuccessTrue SuccessMessageResponseSuccess = true
)

// Defines values for SuccessMountResponseSuccess.
const (
	SuccessMountResponseSuccessTrue SuccessMountResponseSuccess = true
)

// Defines values for SuccessMountStatusResponseSuccess.
const (
	SuccessMountStatusResponseSuccessTrue SuccessMountStatusResponseSuccess = true
)

// Defines values for SuccessMovedResponseSuccess.
const (
	SuccessMovedResponseSuccessTrue SuccessMovedResponseSuccess = true
)

// Defines values for SuccessPauseSandboxResponseSuccess.
const (
	SuccessPauseSandboxResponseSuccessTrue SuccessPauseSandboxResponseSuccess = true
)

// Defines values for SuccessRefreshResponseSuccess.
const (
	SuccessRefreshResponseSuccessTrue SuccessRefreshResponseSuccess = true
)

// Defines values for SuccessResizedResponseSuccess.
const (
	SuccessResizedResponseSuccessTrue SuccessResizedResponseSuccess = true
)

// Defines values for SuccessRestoreResponseSuccess.
const (
	SuccessRestoreResponseSuccessTrue SuccessRestoreResponseSuccess = true
)

// Defines values for SuccessResumeSandboxResponseSuccess.
const (
	SuccessResumeSandboxResponseSuccessTrue SuccessResumeSandboxResponseSuccess = true
)

// Defines values for SuccessSandboxNetworkPolicyResponseSuccess.
const (
	SuccessSandboxNetworkPolicyResponseSuccessTrue SuccessSandboxNetworkPolicyResponseSuccess = true
)

// Defines values for SuccessSandboxResponseSuccess.
const (
	SuccessSandboxResponseSuccessTrue SuccessSandboxResponseSuccess = true
)

// Defines values for SuccessSandboxStatusResponseSuccess.
const (
	SuccessSandboxStatusResponseSuccessTrue SuccessSandboxStatusResponseSuccess = true
)

// Defines values for SuccessSandboxVolumeListResponseSuccess.
const (
	SuccessSandboxVolumeListResponseSuccessTrue SuccessSandboxVolumeListResponseSuccess = true
)

// Defines values for SuccessSandboxVolumeResponseSuccess.
const (
	SuccessSandboxVolumeResponseSuccessTrue SuccessSandboxVolumeResponseSuccess = true
)

// Defines values for SuccessSignaledResponseSuccess.
const (
	SuccessSignaledResponseSuccessTrue SuccessSignaledResponseSuccess = true
)

// Defines values for SuccessSnapshotListResponseSuccess.
const (
	SuccessSnapshotListResponseSuccessTrue SuccessSnapshotListResponseSuccess = true
)

// Defines values for SuccessSnapshotResponseSuccess.
const (
	SuccessSnapshotResponseSuccessTrue SuccessSnapshotResponseSuccess = true
)

// Defines values for SuccessTeamListResponseSuccess.
const (
	SuccessTeamListResponseSuccessTrue SuccessTeamListResponseSuccess = true
)

// Defines values for SuccessTeamMemberListResponseSuccess.
const (
	SuccessTeamMemberListResponseSuccessTrue SuccessTeamMemberListResponseSuccess = true
)

// Defines values for SuccessTeamMemberResponseSuccess.
const (
	SuccessTeamMemberResponseSuccessTrue SuccessTeamMemberResponseSuccess = true
)

// Defines values for SuccessTeamResponseSuccess.
const (
	SuccessTeamResponseSuccessTrue SuccessTeamResponseSuccess = true
)

// Defines values for SuccessTemplateListResponseSuccess.
const (
	SuccessTemplateListResponseSuccessTrue SuccessTemplateListResponseSuccess = true
)

// Defines values for SuccessTemplateResponseSuccess.
const (
	SuccessTemplateResponseSuccessTrue SuccessTemplateResponseSuccess = true
)

// Defines values for SuccessUnmountedResponseSuccess.
const (
	SuccessUnmountedResponseSuccessTrue SuccessUnmountedResponseSuccess = true
)

// Defines values for SuccessUserResponseSuccess.
const (
	SuccessUserResponseSuccessTrue SuccessUserResponseSuccess = true
)

// Defines values for SuccessWrittenResponseSuccess.
const (
	SuccessWrittenResponseSuccessTrue SuccessWrittenResponseSuccess = true
)

// Defines values for TplSandboxNetworkPolicyMode.
const (
	AllowAll TplSandboxNetworkPolicyMode = "allow-all"
	BlockAll TplSandboxNetworkPolicyMode = "block-all"
	Custom   TplSandboxNetworkPolicyMode = "custom"
)

// Defines values for UpdateTeamMemberRequestRole.
const (
	UpdateTeamMemberRequestRoleAdmin     UpdateTeamMemberRequestRole = "admin"
	UpdateTeamMemberRequestRoleDeveloper UpdateTeamMemberRequestRole = "developer"
	UpdateTeamMemberRequestRoleViewer    UpdateTeamMemberRequestRole = "viewer"
)

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt  time.Time  `json:"created_at"`
	CreatedBy  string     `json:"created_by"`
	ExpiresAt  time.Time  `json:"expires_at"`
	Id         string     `json:"id"`
	IsActive   bool       `json:"is_active"`
	KeyValue   *string    `json:"key_value,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Name       string     `json:"name"`
	Roles      []string   `json:"roles"`
	TeamId     string     `json:"team_id"`
	Type       string     `json:"type"`
	UpdatedAt  time.Time  `json:"updated_at"`
	UsageCount *int64     `json:"usage_count,omitempty"`
	UserId     *string    `json:"user_id"`
}

// AccountingSpec defines model for AccountingSpec.
type AccountingSpec struct {
	Enabled               bool   `json:"enabled"`
	ReportIntervalSeconds *int32 `json:"reportIntervalSeconds,omitempty"`
}

// AddTeamMemberRequest defines model for AddTeamMemberRequest.
type AddTeamMemberRequest struct {
	Email openapi_types.Email      `json:"email"`
	Role  AddTeamMemberRequestRole `json:"role"`
}

// AddTeamMemberRequestRole defines model for AddTeamMemberRequest.Role.
type AddTeamMemberRequestRole string

// Affinity defines model for Affinity.
type Affinity struct {
	NodeAffinity *NodeAffinity `json:"nodeAffinity,omitempty"`
	PodAffinity  *PodAffinity  `json:"podAffinity,omitempty"`
}

// AuthProvider defines model for AuthProvider.
type AuthProvider struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// BandwidthPolicySpec defines model for BandwidthPolicySpec.
type BandwidthPolicySpec struct {
	Accounting       *AccountingSpec `json:"accounting,omitempty"`
	EgressRateLimit  *RateLimitSpec  `json:"egressRateLimit,omitempty"`
	IngressRateLimit *RateLimitSpec  `json:"ingressRateLimit,omitempty"`
	SandboxId        *string         `json:"sandboxId,omitempty"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Drop *[]string `json:"drop,omitempty"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// ClaimRequest defines model for ClaimRequest.
type ClaimRequest struct {
	Config   *SandboxConfig `json:"config,omitempty"`
	Template *string        `json:"template,omitempty"`
}

// ClaimResponse defines model for ClaimResponse.
type ClaimResponse struct {
	ClusterId *string `json:"cluster_id"`
	PodName   string  `json:"pod_name"`
	SandboxId string  `json:"sandbox_id"`
	Status    string  `json:"status"`
	Template  string  `json:"template"`
}

// ContainerSpec defines model for ContainerSpec.
type ContainerSpec struct {
	Env             *[]EnvVar        `json:"env,omitempty"`
	Image           string           `json:"image"`
	ImagePullPolicy *string          `json:"imagePullPolicy,omitempty"`
	Resources       ResourceQuota    `json:"resources"`
	SecurityContext *SecurityContext `json:"securityContext,omitempty"`
}

// ContextExecResponse defines model for ContextExecResponse.
type ContextExecResponse struct {
	Output string `json:"output"`
}

// ContextInputRequest defines model for ContextInputRequest.
type ContextInputRequest struct {
	Data string `json:"data"`
}

// ContextResourceUsage defines model for ContextResourceUsage.
type ContextResourceUsage struct {
	ContextId *string        `json:"context_id,omitempty"`
	Language  *string        `json:"language,omitempty"`
	Paused    *bool          `json:"paused,omitempty"`
	Running   *bool          `json:"running,omitempty"`
	Type      *string        `json:"type,omitempty"`
	Usage     *ResourceUsage `json:"usage,omitempty"`
}

// ContextResponse defines model for ContextResponse.
type ContextResponse struct {
	CreatedAt string             `json:"created_at"`
	Cwd       *string            `json:"cwd,omitempty"`
	EnvVars   *map[string]string `json:"env_vars,omitempty"`
	Id        string             `json:"id"`
	Language  *string            `json:"language,omitempty"`
	Output    *string            `json:"output,omitempty"`
	Paused    bool               `json:"paused"`
	Running   bool               `json:"running"`
	Type      ProcessType        `json:"type"`
}

// ContextStatsResponse defines model for ContextStatsResponse.
type ContextStatsResponse struct {
	ContextId *string        `json:"context_id,omitempty"`
	Language  *string        `json:"language,omitempty"`
	Paused    *bool          `json:"paused,omitempty"`
	Running   *bool          `json:"running,omitempty"`
	Type      *string        `json:"type,omitempty"`
	Usage     *ResourceUsage `json:"usage,omitempty"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// ExpiresIn 30d, 90d, 180d, 365d, or never
	ExpiresIn *string                 `json:"expires_in,omitempty"`
	Name      string                  `json:"name"`
	Roles     *[]string               `json:"roles,omitempty"`
	Type      CreateAPIKeyRequestType `json:"type"`
}

// CreateAPIKeyRequestType defines model for CreateAPIKeyRequest.Type.
type CreateAPIKeyRequestType string

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Id        string    `json:"id"`
	Key       *string   `json:"key,omitempty"`
	Name      string    `json:"name"`
	Roles     []string  `json:"roles"`
	TeamId    string    `json:"team_id"`
	Type      string    `json:"type"`
}

// CreateCMDContextRequest defines model for CreateCMDContextRequest.
type CreateCMDContextRequest struct {
	Command *[]string `json:"command,omitempty"`
}

// CreateContextRequest defines model for CreateContextRequest.
type CreateContextRequest struct {
	Cmd            *CreateCMDContextRequest  `json:"cmd,omitempty"`
	Cwd            *string                   `json:"cwd,omitempty"`
	EnvVars        *map[string]string        `json:"env_vars,omitempty"`
	IdleTimeoutSec *int32                    `json:"idle_timeout_sec,omitempty"`
	PtySize        *PTYSize                  `json:"pty_size,omitempty"`
	Repl           *CreateREPLContextRequest `json:"repl,omitempty"`
	TtlSec         *int32                    `json:"ttl_sec,omitempty"`
	Type           *ProcessType              `json:"type,omitempty"`
	WaitUntilDone  *bool                     `json:"wait_until_done,omitempty"`
}

// CreateREPLContextRequest defines model for CreateREPLContextRequest.
type CreateREPLContextRequest struct {
	Input      *string     `json:"input,omitempty"`
	Language   *string     `json:"language,omitempty"`
	ReplConfig *REPLConfig `json:"repl_config,omitempty"`
}

// CreateSandboxVolumeRequest defines model for CreateSandboxVolumeRequest.
type CreateSandboxVolumeRequest struct {
	BufferSize *string `json:"buffer_size,omitempty"`
	CacheSize  *string `json:"cache_size,omitempty"`
	Prefetch   *int    `json:"prefetch,omitempty"`
	ReadOnly   *bool   `json:"read_only,omitempty"`
	Writeback  *bool   `json:"writeback,omitempty"`
}

// CreateSnapshotRequest defines model for CreateSnapshotRequest.
type CreateSnapshotRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

// EnvVar defines model for EnvVar.
type EnvVar struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Error defines model for Error.
type Error struct {
	Code    string       `json:"code"`
	Details *interface{} `json:"details,omitempty"`
	Message string       `json:"message"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error   Error                `json:"error"`
	Success ErrorEnvelopeSuccess `json:"success"`
}

// ErrorEnvelopeSuccess defines model for ErrorEnvelope.Success.
type ErrorEnvelopeSuccess bool

// ExecCandidate defines model for ExecCandidate.
type ExecCandidate struct {
	Args *[]string `json:"args,omitempty"`
	Name string    `json:"name"`
}

// FileContentResponse defines model for FileContentResponse.
type FileContentResponse struct {
	Content  *string                      `json:"content,omitempty"`
	Encoding *FileContentResponseEncoding `json:"encoding,omitempty"`
}

// FileContentResponseEncoding defines model for FileContentResponse.Encoding.
type FileContentResponseEncoding string

// FileInfo defines model for FileInfo.
type FileInfo struct {
	IsLink     *bool         `json:"is_link,omitempty"`
	LinkTarget *string       `json:"link_target,omitempty"`
	ModTime    *time.Time    `json:"mod_time,omitempty"`
	Mode       *string       `json:"mode,omitempty"`
	Name       *string       `json:"name,omitempty"`
	Path       *string       `json:"path,omitempty"`
	Size       *int64        `json:"size,omitempty"`
	Type       *FileInfoType `json:"type,omitempty"`
}

// FileInfoType defines model for FileInfo.Type.
type FileInfoType string

// Identity defines model for Identity.
type Identity struct {
	CreatedAt int64  `json:"created_at"`
	Id        string `json:"id"`
	Provider  string `json:"provider"`
}

// LabelSelector defines model for LabelSelector.
type LabelSelector struct {
	MatchExpressions *[]LabelSelectorRequirement `json:"matchExpressions,omitempty"`
	MatchLabels      *map[string]string          `json:"matchLabels,omitempty"`
}

// LabelSelectorRequirement defines model for LabelSelectorRequirement.
type LabelSelectorRequirement struct {
	Key      string    `json:"key"`
	Operator string    `json:"operator"`
	Values   *[]string `json:"values,omitempty"`
}

// LifecyclePolicy defines model for LifecyclePolicy.
type LifecyclePolicy struct {
	DefaultTTL  *int32       `json:"defaultTTL,omitempty"`
	IdleTimeout *int32       `json:"idleTimeout,omitempty"`
	MaxTTL      *int32       `json:"maxTTL,omitempty"`
	PreStop     *PreStopHook `json:"preStop,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	ExpiresAt    int64  `json:"expires_at"`
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

// MountRequest defines model for MountRequest.
type MountRequest struct {
	MountPoint      string        `json:"mount_point"`
	SandboxId       *string       `json:"sandbox_id,omitempty"`
	SandboxvolumeId string        `json:"sandboxvolume_id"`
	VolumeConfig    *VolumeConfig `json:"volume_config,omitempty"`
}

// MountResponse defines model for MountResponse.
type MountResponse struct {
	MountPoint      string `json:"mount_point"`
	MountedAt       string `json:"mounted_at"`
	SandboxvolumeId string `json:"sandboxvolume_id"`
}

// MountStatus defines model for MountStatus.
type MountStatus struct {
	MountPoint         *string `json:"mount_point,omitempty"`
	MountedAt          *string `json:"mounted_at,omitempty"`
	MountedDurationSec *int64  `json:"mounted_duration_sec,omitempty"`
	SandboxvolumeId    *string `json:"sandboxvolume_id,omitempty"`
}

// MoveFileRequest defines model for MoveFileRequest.
type MoveFileRequest struct {
	Destination string `json:"destination"`
	Source      string `json:"source"`
}

// NetworkEgressPolicy defines model for NetworkEgressPolicy.
type NetworkEgressPolicy struct {
	AllowedDomains *[]string `json:"allowedDomains,omitempty"`
	AllowedIPs     *[]string `json:"allowedIPs,omitempty"`
	BlockedDomains *[]string `json:"blockedDomains,omitempty"`
	BlockedIPs     *[]string `json:"blockedIPs,omitempty"`
}

// NetworkIngressPolicy defines model for NetworkIngressPolicy.
type NetworkIngressPolicy struct {
	AllowedIPs *[]string `json:"allowedIPs,omitempty"`
	BlockedIPs *[]string `json:"blockedIPs,omitempty"`
}

// NodeAffinity defines model for NodeAffinity.
type NodeAffinity struct {
	PreferredDuringSchedulingIgnoredDuringExecution *[]PreferredSchedulingTerm `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`
	RequiredDuringSchedulingIgnoredDuringExecution  *NodeSelector              `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// NodeSelector defines model for NodeSelector.
type NodeSelector struct {
	NodeSelectorTerms *[]NodeSelectorTerm `json:"nodeSelectorTerms,omitempty"`
}

// NodeSelectorRequirement defines model for NodeSelectorRequirement.
type NodeSelectorRequirement struct {
	Key      string    `json:"key"`
	Operator string    `json:"operator"`
	Values   *[]string `json:"values,omitempty"`
}

// NodeSelectorTerm defines model for NodeSelectorTerm.
type NodeSelectorTerm struct {
	MatchExpressions *[]NodeSelectorRequirement `json:"matchExpressions,omitempty"`
	MatchFields      *[]NodeSelectorRequirement `json:"matchFields,omitempty"`
}

// ObjectMeta defines model for ObjectMeta.
type ObjectMeta struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	Labels      *map[string]string `json:"labels,omitempty"`
	Name        *string            `json:"name,omitempty"`
	Namespace   *string            `json:"namespace,omitempty"`
}

// PTYSize defines model for PTYSize.
type PTYSize struct {
	Cols *int32 `json:"cols,omitempty"`
	Rows *int32 `json:"rows,omitempty"`
}

// PauseSandboxResponse defines model for PauseSandboxResponse.
type PauseSandboxResponse struct {
	Paused        bool                  `json:"paused"`
	ResourceUsage *SandboxResourceUsage `json:"resource_usage,omitempty"`
	SandboxId     string                `json:"sandbox_id"`
	UpdatedCpu    *string               `json:"updated_cpu,omitempty"`
	UpdatedMemory *string               `json:"updated_memory,omitempty"`
}

// PodAffinity defines model for PodAffinity.
type PodAffinity struct {
	PreferredDuringSchedulingIgnoredDuringExecution *[]WeightedPodAffinityTerm `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`
	RequiredDuringSchedulingIgnoredDuringExecution  *[]PodAffinityTerm         `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// PodAffinityTerm defines model for PodAffinityTerm.
type PodAffinityTerm struct {
	LabelSelector *LabelSelector `json:"labelSelector,omitempty"`
	Namespaces    *[]string      `json:"namespaces,omitempty"`
	TopologyKey   string         `json:"topologyKey"`
}

// PodSpecOverride defines model for PodSpecOverride.
type PodSpecOverride struct {
	Affinity           *Affinity          `json:"affinity,omitempty"`
	NodeSelector       *map[string]string `json:"nodeSelector,omitempty"`
	ServiceAccountName *string            `json:"serviceAccountName,omitempty"`
	Tolerations        *[]Toleration      `json:"tolerations,omitempty"`
}

// PoolStrategy defines model for PoolStrategy.
type PoolStrategy struct {
	AutoScale bool  `json:"autoScale"`
	MaxIdle   int32 `json:"maxIdle"`
	MinIdle   int32 `json:"minIdle"`
}

// PreStopHook defines model for PreStopHook.
type PreStopHook struct {
	Command        *[]string `json:"command,omitempty"`
	TimeoutSeconds *int32    `json:"timeoutSeconds,omitempty"`
}

// PreferredSchedulingTerm defines model for PreferredSchedulingTerm.
type PreferredSchedulingTerm struct {
	Preference NodeSelectorTerm `json:"preference"`
	Weight     int32            `json:"weight"`
}

// ProcessType defines model for ProcessType.
type ProcessType string

// REPLConfig defines model for REPLConfig.
type REPLConfig struct {
	Candidates  []ExecCandidate   `json:"candidates"`
	DefaultTerm *string           `json:"default_term,omitempty"`
	Description *string           `json:"description,omitempty"`
	DisplayName *string           `json:"display_name,omitempty"`
	Env         *[]REPLEnvVar     `json:"env,omitempty"`
	Name        string            `json:"name"`
	Prompt      *REPLPromptConfig `json:"prompt,omitempty"`
	Ready       *REPLReadyConfig  `json:"ready,omitempty"`
}

// REPLEnvVar defines model for REPLEnvVar.
type REPLEnvVar struct {
	Name      string  `json:"name"`
	Value     *string `json:"value,omitempty"`
	ValueFrom *string `json:"value_from,omitempty"`
}

// REPLPromptConfig defines model for REPLPromptConfig.
type REPLPromptConfig struct {
	CustomPrompt *string `json:"custom_prompt,omitempty"`
}

// REPLReadyConfig defines model for REPLReadyConfig.
type REPLReadyConfig struct {
	Mode           *REPLReadyMode `json:"mode,omitempty"`
	StartupDelayMs *int32         `json:"startup_delay_ms,omitempty"`
	Token          *string        `json:"token,omitempty"`
}

// REPLReadyMode defines model for REPLReadyMode.
type REPLReadyMode string

// RateLimitSpec defines model for RateLimitSpec.
type RateLimitSpec struct {
	BurstBytes *int64 `json:"burstBytes,omitempty"`
	CeilBps    *int64 `json:"ceilBps,omitempty"`
	RateBps    int64  `json:"rateBps"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	SandboxId string    `json:"sandbox_id"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// ResizeContextRequest defines model for ResizeContextRequest.
type ResizeContextRequest struct {
	Cols int32 `json:"cols"`
	Rows int32 `json:"rows"`
}

// ResourceQuota defines model for ResourceQuota.
type ResourceQuota struct {
	Cpu    *string `json:"cpu,omitempty"`
	Memory *string `json:"memory,omitempty"`
}

// ResourceUsage defines model for ResourceUsage.
type ResourceUsage struct {
	ContainerMemoryLimit      *int64   `json:"container_memory_limit,omitempty"`
	ContainerMemoryUsage      *int64   `json:"container_memory_usage,omitempty"`
	ContainerMemoryWorkingSet *int64   `json:"container_memory_working_set,omitempty"`
	CpuPercent                *float64 `json:"cpu_percent,omitempty"`
	IoReadBytes               *int64   `json:"io_read_bytes,omitempty"`
	IoWriteBytes              *int64   `json:"io_write_bytes,omitempty"`
	MemoryBytes               *int64   `json:"memory_bytes,omitempty"`
	MemoryRss                 *int64   `json:"memory_rss,omitempty"`
	MemoryVms                 *int64   `json:"memory_vms,omitempty"`
	OpenFiles                 *int     `json:"open_files,omitempty"`
	ThreadCount               *int     `json:"thread_count,omitempty"`
}

// ResumeSandboxResponse defines model for ResumeSandboxResponse.
type ResumeSandboxResponse struct {
	RestoredMemory *string `json:"restored_memory,omitempty"`
	Resumed        bool    `json:"resumed"`
	SandboxId      string  `json:"sandbox_id"`
}

// Sandbox defines model for Sandbox.
type Sandbox struct {
	ClaimedAt  time.Time `json:"claimed_at"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	Id         string    `json:"id"`
	PodName    string    `json:"pod_name"`
	Status     string    `json:"status"`
	TeamId     string    `json:"team_id"`
	TemplateId string    `json:"template_id"`
	UserId     *string   `json:"user_id,omitempty"`
}

// SandboxConfig defines model for SandboxConfig.
type SandboxConfig struct {
	EnvVars *map[string]string       `json:"env_vars,omitempty"`
	Network *TplSandboxNetworkPolicy `json:"network,omitempty"`
	Ttl     *int32                   `json:"ttl,omitempty"`
	Webhook *WebhookConfig           `json:"webhook,omitempty"`
}

// SandboxResourceUsage defines model for SandboxResourceUsage.
type SandboxResourceUsage struct {
	ContainerMemoryLimit      *int64                  `json:"container_memory_limit,omitempty"`
	ContainerMemoryUsage      *int64                  `json:"container_memory_usage,omitempty"`
	ContainerMemoryWorkingSet *int64                  `json:"container_memory_working_set,omitempty"`
	ContextCount              *int                    `json:"context_count,omitempty"`
	Contexts                  *[]ContextResourceUsage `json:"contexts,omitempty"`
	PausedContextCount        *int                    `json:"paused_context_count,omitempty"`
	RunningContextCount       *int                    `json:"running_context_count,omitempty"`
	TotalIoReadBytes          *int64                  `json:"total_io_read_bytes,omitempty"`
	TotalIoWriteBytes         *int64                  `json:"total_io_write_bytes,omitempty"`
	TotalMemoryRss            *int64                  `json:"total_memory_rss,omitempty"`
	TotalMemoryVms            *int64                  `json:"total_memory_vms,omitempty"`
	TotalOpenFiles            *int                    `json:"total_open_files,omitempty"`
	TotalThreadCount          *int                    `json:"total_thread_count,omitempty"`
}

// SandboxStatus defines model for SandboxStatus.
type SandboxStatus struct {
	ClaimedAt  *string `json:"claimed_at,omitempty"`
	CreatedAt  *string `json:"created_at,omitempty"`
	ExpiresAt  *string `json:"expires_at,omitempty"`
	PodName    *string `json:"pod_name,omitempty"`
	SandboxId  *string `json:"sandbox_id,omitempty"`
	Status     *string `json:"status,omitempty"`
	TeamId     *string `json:"team_id,omitempty"`
	TemplateId *string `json:"template_id,omitempty"`
	UserId     *string `json:"user_id,omitempty"`
}

// SandboxTemplate defines model for SandboxTemplate.
type SandboxTemplate struct {
	ApiVersion *string                `json:"apiVersion,omitempty"`
	Kind       *string                `json:"kind,omitempty"`
	Metadata   *ObjectMeta            `json:"metadata,omitempty"`
	Spec       *SandboxTemplateSpec   `json:"spec,omitempty"`
	Status     *SandboxTemplateStatus `json:"status,omitempty"`
}

// SandboxTemplateCondition defines model for SandboxTemplateCondition.
type SandboxTemplateCondition struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// SandboxTemplateSpec defines model for SandboxTemplateSpec.
type SandboxTemplateSpec struct {
	AllowedTeams     *[]string                `json:"allowedTeams,omitempty"`
	ClusterId        *string                  `json:"clusterId,omitempty"`
	Description      *string                  `json:"description,omitempty"`
	DisplayName      *string                  `json:"displayName,omitempty"`
	EnvVars          *map[string]string       `json:"envVars,omitempty"`
	Lifecycle        *LifecyclePolicy         `json:"lifecycle,omitempty"`
	MainContainer    *ContainerSpec           `json:"mainContainer,omitempty"`
	Network          *TplSandboxNetworkPolicy `json:"network,omitempty"`
	Pod              *PodSpecOverride         `json:"pod,omitempty"`
	Pool             *PoolStrategy            `json:"pool,omitempty"`
	Public           *bool                    `json:"public,omitempty"`
	RuntimeClassName *string                  `json:"runtimeClassName,omitempty"`
	Sidecars         *[]ContainerSpec         `json:"sidecars,omitempty"`
	Tags             *[]string                `json:"tags,omitempty"`
}

// SandboxTemplateStatus defines model for SandboxTemplateStatus.
type SandboxTemplateStatus struct {
	ActiveCount    *int32                      `json:"activeCount,omitempty"`
	Conditions     *[]SandboxTemplateCondition `json:"conditions,omitempty"`
	IdleCount      *int32                      `json:"idleCount,omitempty"`
	LastUpdateTime *time.Time                  `json:"lastUpdateTime,omitempty"`
}

// SandboxUpdateRequest defines model for SandboxUpdateRequest.
type SandboxUpdateRequest struct {
	Config *SandboxConfig `json:"config,omitempty"`
}

// SandboxVolume defines model for SandboxVolume.
type SandboxVolume struct {
	BufferSize string    `json:"buffer_size"`
	CacheSize  string    `json:"cache_size"`
	CreatedAt  time.Time `json:"created_at"`
	Id         string    `json:"id"`
	Prefetch   *int      `json:"prefetch,omitempty"`
	ReadOnly   *bool     `json:"read_only,omitempty"`
	TeamId     string    `json:"team_id"`
	UpdatedAt  time.Time `json:"updated_at"`
	UserId     string    `json:"user_id"`
	Writeback  *bool     `json:"writeback,omitempty"`
}

// SecurityContext defines model for SecurityContext.
type SecurityContext struct {
	Capabilities *Capabilities `json:"capabilities,omitempty"`
	RunAsGroup   *int64        `json:"runAsGroup,omitempty"`
	RunAsUser    *int64        `json:"runAsUser,omitempty"`
}

// SignalContextRequest defines model for SignalContextRequest.
type SignalContextRequest struct {
	Signal string `json:"signal"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CreatedAt   string  `json:"created_at"`
	Description *string `json:"description,omitempty"`
	ExpiresAt   *string `json:"expires_at"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	SizeBytes   int64   `json:"size_bytes"`
	VolumeId    string  `json:"volume_id"`
}

// SuccessAPIKeyListResponse defines model for SuccessAPIKeyListResponse.
type SuccessAPIKeyListResponse struct {
	Data *struct {
		ApiKeys *[]APIKey `json:"api_keys,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessAPIKeyListResponseSuccess `json:"success"`
}

// SuccessAPIKeyListResponseSuccess defines model for SuccessAPIKeyListResponse.Success.
type SuccessAPIKeyListResponseSuccess bool

// SuccessAuthProvidersResponse defines model for SuccessAuthProvidersResponse.
type SuccessAuthProvidersResponse struct {
	Data *struct {
		Providers *[]AuthProvider `json:"providers,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessAuthProvidersResponseSuccess `json:"success"`
}

// SuccessAuthProvidersResponseSuccess defines model for SuccessAuthProvidersResponse.Success.
type SuccessAuthProvidersResponseSuccess bool

// SuccessBandwidthPolicyResponse defines model for SuccessBandwidthPolicyResponse.
type SuccessBandwidthPolicyResponse struct {
	Data    *BandwidthPolicySpec                  `json:"data,omitempty"`
	Success SuccessBandwidthPolicyResponseSuccess `json:"success"`
}

// SuccessBandwidthPolicyResponseSuccess defines model for SuccessBandwidthPolicyResponse.Success.
type SuccessBandwidthPolicyResponseSuccess bool

// SuccessClaimResponse defines model for SuccessClaimResponse.
type SuccessClaimResponse struct {
	Data    *ClaimResponse              `json:"data,omitempty"`
	Success SuccessClaimResponseSuccess `json:"success"`
}

// SuccessClaimResponseSuccess defines model for SuccessClaimResponse.Success.
type SuccessClaimResponseSuccess bool

// SuccessContextExecResponse defines model for SuccessContextExecResponse.
type SuccessContextExecResponse struct {
	Data    *ContextExecResponse              `json:"data,omitempty"`
	Success SuccessContextExecResponseSuccess `json:"success"`
}

// SuccessContextExecResponseSuccess defines model for SuccessContextExecResponse.Success.
type SuccessContextExecResponseSuccess bool

// SuccessContextListResponse defines model for SuccessContextListResponse.
type SuccessContextListResponse struct {
	Data *struct {
		Contexts *[]ContextResponse `json:"contexts,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessContextListResponseSuccess `json:"success"`
}

// SuccessContextListResponseSuccess defines model for SuccessContextListResponse.Success.
type SuccessContextListResponseSuccess bool

// SuccessContextResponse defines model for SuccessContextResponse.
type SuccessContextResponse struct {
	Data    *ContextResponse              `json:"data,omitempty"`
	Success SuccessContextResponseSuccess `json:"success"`
}

// SuccessContextResponseSuccess defines model for SuccessContextResponse.Success.
type SuccessContextResponseSuccess bool

// SuccessContextStatsResponse defines model for SuccessContextStatsResponse.
type SuccessContextStatsResponse struct {
	Data    *ContextStatsResponse              `json:"data,omitempty"`
	Success SuccessContextStatsResponseSuccess `json:"success"`
}

// SuccessContextStatsResponseSuccess defines model for SuccessContextStatsResponse.Success.
type SuccessContextStatsResponseSuccess bool

// SuccessCreateAPIKeyResponse defines model for SuccessCreateAPIKeyResponse.
type SuccessCreateAPIKeyResponse struct {
	Data    *CreateAPIKeyResponse              `json:"data,omitempty"`
	Success SuccessCreateAPIKeyResponseSuccess `json:"success"`
}

// SuccessCreateAPIKeyResponseSuccess defines model for SuccessCreateAPIKeyResponse.Success.
type SuccessCreateAPIKeyResponseSuccess bool

// SuccessCreatedResponse defines model for SuccessCreatedResponse.
type SuccessCreatedResponse struct {
	Data *struct {
		Created *bool `json:"created,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessCreatedResponseSuccess `json:"success"`
}

// SuccessCreatedResponseSuccess defines model for SuccessCreatedResponse.Success.
type SuccessCreatedResponseSuccess bool

// SuccessDeletedResponse defines model for SuccessDeletedResponse.
type SuccessDeletedResponse struct {
	Data *struct {
		Deleted *bool `json:"deleted,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessDeletedResponseSuccess `json:"success"`
}

// SuccessDeletedResponseSuccess defines model for SuccessDeletedResponse.Success.
type SuccessDeletedResponseSuccess bool

// SuccessEnvelope defines model for SuccessEnvelope.
type SuccessEnvelope struct {
	Data    *interface{}           `json:"data,omitempty"`
	Success SuccessEnvelopeSuccess `json:"success"`
}

// SuccessEnvelopeSuccess defines model for SuccessEnvelope.Success.
type SuccessEnvelopeSuccess bool

// SuccessFileBinaryResponse defines model for SuccessFileBinaryResponse.
type SuccessFileBinaryResponse struct {
	Data    *FileContentResponse             `json:"data,omitempty"`
	Success SuccessFileBinaryResponseSuccess `json:"success"`
}

// SuccessFileBinaryResponseSuccess defines model for SuccessFileBinaryResponse.Success.
type SuccessFileBinaryResponseSuccess bool

// SuccessFileListResponse defines model for SuccessFileListResponse.
type SuccessFileListResponse struct {
	Data *struct {
		Entries *[]FileInfo `json:"entries,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessFileListResponseSuccess `json:"success"`
}

// SuccessFileListResponseSuccess defines model for SuccessFileListResponse.Success.
type SuccessFileListResponseSuccess bool

// SuccessFileStatResponse defines model for SuccessFileStatResponse.
type SuccessFileStatResponse struct {
	Data    *FileInfo                      `json:"data,omitempty"`
	Success SuccessFileStatResponseSuccess `json:"success"`
}

// SuccessFileStatResponseSuccess defines model for SuccessFileStatResponse.Success.
type SuccessFileStatResponseSuccess bool

// SuccessHealthResponse defines model for SuccessHealthResponse.
type SuccessHealthResponse struct {
	Data *struct {
		Status    *string `json:"status,omitempty"`
		Timestamp *int64  `json:"timestamp,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessHealthResponseSuccess `json:"success"`
}

// SuccessHealthResponseSuccess defines model for SuccessHealthResponse.Success.
type SuccessHealthResponseSuccess bool

// SuccessIdentityListResponse defines model for SuccessIdentityListResponse.
type SuccessIdentityListResponse struct {
	Data *struct {
		Identities *[]Identity `json:"identities,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessIdentityListResponseSuccess `json:"success"`
}

// SuccessIdentityListResponseSuccess defines model for SuccessIdentityListResponse.Success.
type SuccessIdentityListResponseSuccess bool

// SuccessLoginResponse defines model for SuccessLoginResponse.
type SuccessLoginResponse struct {
	Data    *LoginResponse              `json:"data,omitempty"`
	Success SuccessLoginResponseSuccess `json:"success"`
}

// SuccessLoginResponseSuccess defines model for SuccessLoginResponse.Success.
type SuccessLoginResponseSuccess bool

// SuccessMessageResponse defines model for SuccessMessageResponse.
type SuccessMessageResponse struct {
	Data *struct {
		Message *string `json:"message,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessMessageResponseSuccess `json:"success"`
}

// SuccessMessageResponseSuccess defines model for SuccessMessageResponse.Success.
type SuccessMessageResponseSuccess bool

// SuccessMountResponse defines model for SuccessMountResponse.
type SuccessMountResponse struct {
	Data    *MountResponse              `json:"data,omitempty"`
	Success SuccessMountResponseSuccess `json:"success"`
}

// SuccessMountResponseSuccess defines model for SuccessMountResponse.Success.
type SuccessMountResponseSuccess bool

// SuccessMountStatusResponse defines model for SuccessMountStatusResponse.
type SuccessMountStatusResponse struct {
	Data *struct {
		Mounts *[]MountStatus `json:"mounts,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessMountStatusResponseSuccess `json:"success"`
}

// SuccessMountStatusResponseSuccess defines model for SuccessMountStatusResponse.Success.
type SuccessMountStatusResponseSuccess bool

// SuccessMovedResponse defines model for SuccessMovedResponse.
type SuccessMovedResponse struct {
	Data *struct {
		Moved *bool `json:"moved,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessMovedResponseSuccess `json:"success"`
}

// SuccessMovedResponseSuccess defines model for SuccessMovedResponse.Success.
type SuccessMovedResponseSuccess bool

// SuccessPauseSandboxResponse defines model for SuccessPauseSandboxResponse.
type SuccessPauseSandboxResponse struct {
	Data    *PauseSandboxResponse              `json:"data,omitempty"`
	Success SuccessPauseSandboxResponseSuccess `json:"success"`
}

// SuccessPauseSandboxResponseSuccess defines model for SuccessPauseSandboxResponse.Success.
type SuccessPauseSandboxResponseSuccess bool

// SuccessRefreshResponse defines model for SuccessRefreshResponse.
type SuccessRefreshResponse struct {
	Data    *RefreshResponse              `json:"data,omitempty"`
	Success SuccessRefreshResponseSuccess `json:"success"`
}

// SuccessRefreshResponseSuccess defines model for SuccessRefreshResponse.Success.
type SuccessRefreshResponseSuccess bool

// SuccessResizedResponse defines model for SuccessResizedResponse.
type SuccessResizedResponse struct {
	Data *struct {
		Resized *bool `json:"resized,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessResizedResponseSuccess `json:"success"`
}

// SuccessResizedResponseSuccess defines model for SuccessResizedResponse.Success.
type SuccessResizedResponseSuccess bool

// SuccessRestoreResponse defines model for SuccessRestoreResponse.
type SuccessRestoreResponse struct {
	Data *struct {
		Status *string `json:"status,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessRestoreResponseSuccess `json:"success"`
}

// SuccessRestoreResponseSuccess defines model for SuccessRestoreResponse.Success.
type SuccessRestoreResponseSuccess bool

// SuccessResumeSandboxResponse defines model for SuccessResumeSandboxResponse.
type SuccessResumeSandboxResponse struct {
	Data    *ResumeSandboxResponse              `json:"data,omitempty"`
	Success SuccessResumeSandboxResponseSuccess `json:"success"`
}

// SuccessResumeSandboxResponseSuccess defines model for SuccessResumeSandboxResponse.Success.
type SuccessResumeSandboxResponseSuccess bool

// SuccessSandboxNetworkPolicyResponse defines model for SuccessSandboxNetworkPolicyResponse.
type SuccessSandboxNetworkPolicyResponse struct {
	Data    *TplSandboxNetworkPolicy                   `json:"data,omitempty"`
	Success SuccessSandboxNetworkPolicyResponseSuccess `json:"success"`
}

// SuccessSandboxNetworkPolicyResponseSuccess defines model for SuccessSandboxNetworkPolicyResponse.Success.
type SuccessSandboxNetworkPolicyResponseSuccess bool

// SuccessSandboxResponse defines model for SuccessSandboxResponse.
type SuccessSandboxResponse struct {
	Data    *Sandbox                      `json:"data,omitempty"`
	Success SuccessSandboxResponseSuccess `json:"success"`
}

// SuccessSandboxResponseSuccess defines model for SuccessSandboxResponse.Success.
type SuccessSandboxResponseSuccess bool

// SuccessSandboxStatusResponse defines model for SuccessSandboxStatusResponse.
type SuccessSandboxStatusResponse struct {
	Data    *SandboxStatus                      `json:"data,omitempty"`
	Success SuccessSandboxStatusResponseSuccess `json:"success"`
}

// SuccessSandboxStatusResponseSuccess defines model for SuccessSandboxStatusResponse.Success.
type SuccessSandboxStatusResponseSuccess bool

// SuccessSandboxVolumeListResponse defines model for SuccessSandboxVolumeListResponse.
type SuccessSandboxVolumeListResponse struct {
	Data    *[]SandboxVolume                        `json:"data,omitempty"`
	Success SuccessSandboxVolumeListResponseSuccess `json:"success"`
}

// SuccessSandboxVolumeListResponseSuccess defines model for SuccessSandboxVolumeListResponse.Success.
type SuccessSandboxVolumeListResponseSuccess bool

// SuccessSandboxVolumeResponse defines model for SuccessSandboxVolumeResponse.
type SuccessSandboxVolumeResponse struct {
	Data    *SandboxVolume                      `json:"data,omitempty"`
	Success SuccessSandboxVolumeResponseSuccess `json:"success"`
}

// SuccessSandboxVolumeResponseSuccess defines model for SuccessSandboxVolumeResponse.Success.
type SuccessSandboxVolumeResponseSuccess bool

// SuccessSignaledResponse defines model for SuccessSignaledResponse.
type SuccessSignaledResponse struct {
	Data *struct {
		Signaled *bool `json:"signaled,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessSignaledResponseSuccess `json:"success"`
}

// SuccessSignaledResponseSuccess defines model for SuccessSignaledResponse.Success.
type SuccessSignaledResponseSuccess bool

// SuccessSnapshotListResponse defines model for SuccessSnapshotListResponse.
type SuccessSnapshotListResponse struct {
	Data    *[]Snapshot                        `json:"data,omitempty"`
	Success SuccessSnapshotListResponseSuccess `json:"success"`
}

// SuccessSnapshotListResponseSuccess defines model for SuccessSnapshotListResponse.Success.
type SuccessSnapshotListResponseSuccess bool

// SuccessSnapshotResponse defines model for SuccessSnapshotResponse.
type SuccessSnapshotResponse struct {
	Data    *Snapshot                      `json:"data,omitempty"`
	Success SuccessSnapshotResponseSuccess `json:"success"`
}

// SuccessSnapshotResponseSuccess defines model for SuccessSnapshotResponse.Success.
type SuccessSnapshotResponseSuccess bool

// SuccessTeamListResponse defines model for SuccessTeamListResponse.
type SuccessTeamListResponse struct {
	Data *struct {
		Teams *[]Team `json:"teams,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessTeamListResponseSuccess `json:"success"`
}

// SuccessTeamListResponseSuccess defines model for SuccessTeamListResponse.Success.
type SuccessTeamListResponseSuccess bool

// SuccessTeamMemberListResponse defines model for SuccessTeamMemberListResponse.
type SuccessTeamMemberListResponse struct {
	Data *struct {
		Members *[]TeamMember `json:"members,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessTeamMemberListResponseSuccess `json:"success"`
}

// SuccessTeamMemberListResponseSuccess defines model for SuccessTeamMemberListResponse.Success.
type SuccessTeamMemberListResponseSuccess bool

// SuccessTeamMemberResponse defines model for SuccessTeamMemberResponse.
type SuccessTeamMemberResponse struct {
	Data    *TeamMember                      `json:"data,omitempty"`
	Success SuccessTeamMemberResponseSuccess `json:"success"`
}

// SuccessTeamMemberResponseSuccess defines model for SuccessTeamMemberResponse.Success.
type SuccessTeamMemberResponseSuccess bool

// SuccessTeamResponse defines model for SuccessTeamResponse.
type SuccessTeamResponse struct {
	Data    *Team                      `json:"data,omitempty"`
	Success SuccessTeamResponseSuccess `json:"success"`
}

// SuccessTeamResponseSuccess defines model for SuccessTeamResponse.Success.
type SuccessTeamResponseSuccess bool

// SuccessTemplateListResponse defines model for SuccessTemplateListResponse.
type SuccessTemplateListResponse struct {
	Data *struct {
		Count     *int               `json:"count,omitempty"`
		Templates *[]SandboxTemplate `json:"templates,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessTemplateListResponseSuccess `json:"success"`
}

// SuccessTemplateListResponseSuccess defines model for SuccessTemplateListResponse.Success.
type SuccessTemplateListResponseSuccess bool

// SuccessTemplateResponse defines model for SuccessTemplateResponse.
type SuccessTemplateResponse struct {
	Data    *SandboxTemplate               `json:"data,omitempty"`
	Success SuccessTemplateResponseSuccess `json:"success"`
}

// SuccessTemplateResponseSuccess defines model for SuccessTemplateResponse.Success.
type SuccessTemplateResponseSuccess bool

// SuccessUnmountedResponse defines model for SuccessUnmountedResponse.
type SuccessUnmountedResponse struct {
	Data *struct {
		Unmounted *bool `json:"unmounted,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessUnmountedResponseSuccess `json:"success"`
}

// SuccessUnmountedResponseSuccess defines model for SuccessUnmountedResponse.Success.
type SuccessUnmountedResponseSuccess bool

// SuccessUserResponse defines model for SuccessUserResponse.
type SuccessUserResponse struct {
	Data    *User                      `json:"data,omitempty"`
	Success SuccessUserResponseSuccess `json:"success"`
}

// SuccessUserResponseSuccess defines model for SuccessUserResponse.Success.
type SuccessUserResponseSuccess bool

// SuccessWrittenResponse defines model for SuccessWrittenResponse.
type SuccessWrittenResponse struct {
	Data *struct {
		Written *bool `json:"written,omitempty"`
	} `json:"data,omitempty"`
	Success SuccessWrittenResponseSuccess `json:"success"`
}

// SuccessWrittenResponseSuccess defines model for SuccessWrittenResponse.Success.
type SuccessWrittenResponseSuccess bool

// Team defines model for Team.
type Team struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	OwnerId   *string   `json:"owner_id"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	Id       string    `json:"id"`
	JoinedAt time.Time `json:"joined_at"`
	Role     string    `json:"role"`
	TeamId   string    `json:"team_id"`
	UserId   string    `json:"user_id"`
}

// Toleration defines model for Toleration.
type Toleration struct {
	Effect   *string `json:"effect,omitempty"`
	Key      *string `json:"key,omitempty"`
	Operator *string `json:"operator,omitempty"`
	Value    *string `json:"value,omitempty"`
}

// TplSandboxNetworkPolicy defines model for TplSandboxNetworkPolicy.
type TplSandboxNetworkPolicy struct {
	Egress  *NetworkEgressPolicy        `json:"egress,omitempty"`
	Ingress *NetworkIngressPolicy       `json:"ingress,omitempty"`
	Mode    TplSandboxNetworkPolicyMode `json:"mode"`
}

// TplSandboxNetworkPolicyMode defines model for TplSandboxNetworkPolicy.Mode.
type TplSandboxNetworkPolicyMode string

// UnmountRequest defines model for UnmountRequest.
type UnmountRequest struct {
	SandboxvolumeId string `json:"sandboxvolume_id"`
}

// UpdateTeamMemberRequest defines model for UpdateTeamMemberRequest.
type UpdateTeamMemberRequest struct {
	Role UpdateTeamMemberRequestRole `json:"role"`
}

// UpdateTeamMemberRequestRole defines model for UpdateTeamMemberRequest.Role.
type UpdateTeamMemberRequestRole string

// UpdateTeamRequest defines model for UpdateTeamRequest.
type UpdateTeamRequest struct {
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	AvatarUrl     *string `json:"avatar_url,omitempty"`
	DefaultTeamId *string `json:"default_team_id"`
	Name          *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl     *string             `json:"avatar_url"`
	CreatedAt     time.Time           `json:"created_at"`
	DefaultTeamId *string             `json:"default_team_id"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            string              `json:"id"`
	IsAdmin       bool                `json:"is_admin"`
	Name          string              `json:"name"`
	UpdatedAt     time.Time           `json:"updated_at"`
}

// VolumeConfig defines model for VolumeConfig.
type VolumeConfig struct {
	BufferSize *string `json:"buffer_size,omitempty"`
	CacheSize  *string `json:"cache_size,omitempty"`
	Prefetch   *int32  `json:"prefetch,omitempty"`
	ReadOnly   *bool   `json:"read_only,omitempty"`
	Writeback  *bool   `json:"writeback,omitempty"`
}

// WarmPoolRequest defines model for WarmPoolRequest.
type WarmPoolRequest struct {
	Count int32 `json:"count"`
}

// WebhookConfig defines model for WebhookConfig.
type WebhookConfig struct {
	Secret *string `json:"secret,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// WeightedPodAffinityTerm defines model for WeightedPodAffinityTerm.
type WeightedPodAffinityTerm struct {
	PodAffinityTerm PodAffinityTerm `json:"podAffinityTerm"`
	Weight          int32           `json:"weight"`
}

// APIKeyID defines model for APIKeyID.
type APIKeyID = string

// ContextID defines model for ContextID.
type ContextID = string

// FilePath defines model for FilePath.
type FilePath = string

// IdentityID defines model for IdentityID.
type IdentityID = string

// OIDCProvider defines model for OIDCProvider.
type OIDCProvider = string

// QueryMkdir defines model for QueryMkdir.
type QueryMkdir = bool

// QueryRecursive defines model for QueryRecursive.
type QueryRecursive = bool

// SandboxID defines model for SandboxID.
type SandboxID = string

// SandboxVolumeID defines model for SandboxVolumeID.
type SandboxVolumeID = string

// SnapshotID defines model for SnapshotID.
type SnapshotID = string

// TeamID defines model for TeamID.
type TeamID = string

// TemplateID defines model for TemplateID.
type TemplateID = string

// UserID defines model for UserID.
type UserID = string

// DeleteApiV1SandboxesIdFilesParams defines parameters for DeleteApiV1SandboxesIdFiles.
type DeleteApiV1SandboxesIdFilesParams struct {
	Path FilePath `form:"path" json:"path"`
}

// GetApiV1SandboxesIdFilesParams defines parameters for GetApiV1SandboxesIdFiles.
type GetApiV1SandboxesIdFilesParams struct {
	Path FilePath `form:"path" json:"path"`
}

// PostApiV1SandboxesIdFilesParams defines parameters for PostApiV1SandboxesIdFiles.
type PostApiV1SandboxesIdFilesParams struct {
	Path      FilePath        `form:"path" json:"path"`
	Mkdir     *QueryMkdir     `form:"mkdir,omitempty" json:"mkdir,omitempty"`
	Recursive *QueryRecursive `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// GetApiV1SandboxesIdFilesBinaryParams defines parameters for GetApiV1SandboxesIdFilesBinary.
type GetApiV1SandboxesIdFilesBinaryParams struct {
	Path FilePath `form:"path" json:"path"`
}

// GetApiV1SandboxesIdFilesListParams defines parameters for GetApiV1SandboxesIdFilesList.
type GetApiV1SandboxesIdFilesListParams struct {
	Path FilePath `form:"path" json:"path"`
}

// GetApiV1SandboxesIdFilesStatParams defines parameters for GetApiV1SandboxesIdFilesStat.
type GetApiV1SandboxesIdFilesStatParams struct {
	Path FilePath `form:"path" json:"path"`
}

// GetAuthOidcProviderCallbackParams defines parameters for GetAuthOidcProviderCallback.
type GetAuthOidcProviderCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// GetAuthOidcProviderLoginParams defines parameters for GetAuthOidcProviderLogin.
type GetAuthOidcProviderLoginParams struct {
	ReturnUrl *string `form:"return_url,omitempty" json:"return_url,omitempty"`
}

// PostApiKeysJSONRequestBody defines body for PostApiKeys for application/json ContentType.
type PostApiKeysJSONRequestBody = CreateAPIKeyRequest

// PostApiV1SandboxesJSONRequestBody defines body for PostApiV1Sandboxes for application/json ContentType.
type PostApiV1SandboxesJSONRequestBody = ClaimRequest

// PatchApiV1SandboxesIdJSONRequestBody defines body for PatchApiV1SandboxesId for application/json ContentType.
type PatchApiV1SandboxesIdJSONRequestBody = SandboxUpdateRequest

// PatchApiV1SandboxesIdBandwidthJSONRequestBody defines body for PatchApiV1SandboxesIdBandwidth for application/json ContentType.
type PatchApiV1SandboxesIdBandwidthJSONRequestBody = BandwidthPolicySpec

// PostApiV1SandboxesIdContextsJSONRequestBody defines body for PostApiV1SandboxesIdContexts for application/json ContentType.
type PostApiV1SandboxesIdContextsJSONRequestBody = CreateContextRequest

// PostApiV1SandboxesIdContextsCtxIdExecJSONRequestBody defines body for PostApiV1SandboxesIdContextsCtxIdExec for application/json ContentType.
type PostApiV1SandboxesIdContextsCtxIdExecJSONRequestBody = ContextInputRequest

// PostApiV1SandboxesIdContextsCtxIdInputJSONRequestBody defines body for PostApiV1SandboxesIdContextsCtxIdInput for application/json ContentType.
type PostApiV1SandboxesIdContextsCtxIdInputJSONRequestBody = ContextInputRequest

// PostApiV1SandboxesIdContextsCtxIdResizeJSONRequestBody defines body for PostApiV1SandboxesIdContextsCtxIdResize for application/json ContentType.
type PostApiV1SandboxesIdContextsCtxIdResizeJSONRequestBody = ResizeContextRequest

// PostApiV1SandboxesIdContextsCtxIdSignalJSONRequestBody defines body for PostApiV1SandboxesIdContextsCtxIdSignal for application/json ContentType.
type PostApiV1SandboxesIdContextsCtxIdSignalJSONRequestBody = SignalContextRequest

// PostApiV1SandboxesIdFilesMoveJSONRequestBody defines body for PostApiV1SandboxesIdFilesMove for application/json ContentType.
type PostApiV1SandboxesIdFilesMoveJSONRequestBody = MoveFileRequest

// PatchApiV1SandboxesIdNetworkJSONRequestBody defines body for PatchApiV1SandboxesIdNetwork for application/json ContentType.
type PatchApiV1SandboxesIdNetworkJSONRequestBody = TplSandboxNetworkPolicy

// PostApiV1SandboxesIdRefreshJSONRequestBody defines body for PostApiV1SandboxesIdRefresh for application/json ContentType.
type PostApiV1SandboxesIdRefreshJSONRequestBody = RefreshRequest

// PostApiV1SandboxesIdSandboxvolumesMountJSONRequestBody defines body for PostApiV1SandboxesIdSandboxvolumesMount for application/json ContentType.
type PostApiV1SandboxesIdSandboxvolumesMountJSONRequestBody = MountRequest

// PostApiV1SandboxesIdSandboxvolumesUnmountJSONRequestBody defines body for PostApiV1SandboxesIdSandboxvolumesUnmount for application/json ContentType.
type PostApiV1SandboxesIdSandboxvolumesUnmountJSONRequestBody = UnmountRequest

// PostApiV1SandboxvolumesJSONRequestBody defines body for PostApiV1Sandboxvolumes for application/json ContentType.
type PostApiV1SandboxvolumesJSONRequestBody = CreateSandboxVolumeRequest

// PostApiV1SandboxvolumesIdSnapshotsJSONRequestBody defines body for PostApiV1SandboxvolumesIdSnapshots for application/json ContentType.
type PostApiV1SandboxvolumesIdSnapshotsJSONRequestBody = CreateSnapshotRequest

// PostApiV1TemplatesJSONRequestBody defines body for PostApiV1Templates for application/json ContentType.
type PostApiV1TemplatesJSONRequestBody = SandboxTemplate

// PutApiV1TemplatesIdJSONRequestBody defines body for PutApiV1TemplatesId for application/json ContentType.
type PutApiV1TemplatesIdJSONRequestBody = SandboxTemplate

// PostApiV1TemplatesIdPoolWarmJSONRequestBody defines body for PostApiV1TemplatesIdPoolWarm for application/json ContentType.
type PostApiV1TemplatesIdPoolWarmJSONRequestBody = WarmPoolRequest

// PostAuthChangePasswordJSONRequestBody defines body for PostAuthChangePassword for application/json ContentType.
type PostAuthChangePasswordJSONRequestBody = ChangePasswordRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostTeamsJSONRequestBody defines body for PostTeams for application/json ContentType.
type PostTeamsJSONRequestBody = CreateTeamRequest

// PutTeamsIdJSONRequestBody defines body for PutTeamsId for application/json ContentType.
type PutTeamsIdJSONRequestBody = UpdateTeamRequest

// PostTeamsIdMembersJSONRequestBody defines body for PostTeamsIdMembers for application/json ContentType.
type PostTeamsIdMembersJSONRequestBody = AddTeamMemberRequest

// PutTeamsIdMembersUserIdJSONRequestBody defines body for PutTeamsIdMembersUserId for application/json ContentType.
type PutTeamsIdMembersUserIdJSONRequestBody = UpdateTeamMemberRequest

// PutUsersMeJSONRequestBody defines body for PutUsersMe for application/json ContentType.
type PutUsersMeJSONRequestBody = UpdateUserRequest
